(function(){
  const KEY='haute-couture-game-state-v1';
  const VERSION=3;
  const clone=o=>JSON.parse(JSON.stringify(o));
  const nowISO=()=>new Date().toISOString();
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const starterInventory=[
    {id:'machine-basic',type:'equipment',name:'Machine à coudre familiale',qty:1,quality:1,memory:'Ta toute première machine.'},
    {id:'scissors-basic',type:'equipment',name:'Ciseaux de couture',qty:1,quality:1},
    {id:'needles-basic',type:'haberdashery',name:'Aiguilles assorties',qty:1,quality:1},
    {id:'thread-neutral',type:'haberdashery',name:'Fils neutres',qty:4,quality:1},
    {id:'fabric-cotton-cream',type:'fabric',name:'Coton écru',qty:2,unit:'m',quality:1}
  ];
  const starterMissionTemplates=[
    {id:'retouche-voisine',kind:'retouche',title:'Une première retouche',clientId:'lucie-voisine',client:'Lucie, ta voisine',relationshipKind:'voisinage',brief:'Raccourcir et reprendre une robe simple pour qu’elle tombe mieux.',budget:55,durationHours:4,difficulty:1,deadlineDays:3,inspiration:'Gestes simples et précision du quotidien',rewards:{money:55,reputationLocal:2,relationship:8,skill:'Couture',skillXp:2}},
    {id:'jupe-simple',kind:'commande',title:'Une jupe pour un dîner',clientId:'emma-cliente',client:'Emma, première cliente',relationshipKind:'cliente',brief:'Créer une jupe simple, portable et bien finie à partir d’un tissu accessible.',budget:95,durationHours:7,difficulty:1,deadlineDays:5,inspiration:'Silhouette de soirée sobre et mouvement',rewards:{money:95,reputationLocal:3,relationship:10,skill:'Finitions',skillXp:2}},
    {id:'transformation-vintage',kind:'upcycling',title:'Transformer une pièce ancienne',clientId:'nora-passage',client:'Nora, cliente de passage',relationshipKind:'cliente',brief:'Donner une nouvelle vie à un vêtement ancien sans perdre son caractère.',budget:80,durationHours:6,difficulty:1,deadlineDays:4,inspiration:'Patine, mémoire textile et transformation',rewards:{money:80,reputationCreative:2,relationship:7,skill:'Créativité',skillXp:2}}
  ];
  const neighborhoodSeeds=[
    {kind:'cafe',name:'Petit café du quartier',bonus:'calme',text:'Un lieu où souffler, observer les gens et noter des idées.'},
    {kind:'mercerie',name:'Mercerie de proximité',bonus:'matieres',text:'Quelques essentiels et parfois une jolie trouvaille.'},
    {kind:'marche',name:'Marché local',bonus:'inspiration',text:'Couleurs, matières, silhouettes et conversations.'},
    {kind:'promenade',name:'Rue à observer',bonus:'inspiration',text:'Façades, passants et lumière changent selon l’heure.'}
  ];
  const surprisePool=[
    {kind:'delivery',title:'Un petit colis',text:'Un échantillon textile a été glissé dans ta boîte aux lettres.',effect:'inspiration'},
    {kind:'neighbor',title:'On frappe à la porte',text:'Une voisine te demande si tu fais aussi les petites retouches.',effect:'mission'},
    {kind:'machine',title:'Un bruit étrange',text:'Ta machine demande un peu d’attention avant de continuer.',effect:'stress'},
    {kind:'weather',title:'Une lumière inattendue',text:'La lumière dehors transforme totalement l’ambiance de la pièce.',effect:'inspiration'}
  ];
  function makeContactFromMission(m){return{id:m.clientId,name:m.client,kind:m.relationshipKind||'contact',relationship:0,status:'Nouveau contact',notes:[],metDay:null,lastInteractionDay:null,trust:0,referrals:0};}
  function baseState(character,residence){
    return {
      version:VERSION,createdAt:nowISO(),updatedAt:nowISO(),started:false,
      player:{characterId:character?.id||null,name:character?.name||'',money:1200,energy:100,stress:10,mood:'Curieuse',creativeFlow:35,confidence:45,reputation:{local:0,professional:0,creative:0,prestige:0,clientele:0,wedding:0,stage:0,luxury:0}},
      world:{day:1,hour:9,minute:0,season:'Automne',weather:'Doux',currentCity:residence?.city||null,currentRegion:residence?.region||null,currentDepartment:residence?.department||null},
      home:{current:residence||null,properties:residence?[residence]:[],primaryResidenceId:residence?.id||null,primaryAtelierId:residence?.id||null,decor:[],equipmentSlots:[],storageBonus:0,memories:[{id:'movein',day:1,title:'Premier emménagement',text:'Quelques cartons, une machine et beaucoup d’idées.'}],objects:[{id:'first-table',name:'Première table de travail',story:'C’est ici que tout commence.',sentimental:1}]},
      inventory:clone(starterInventory),
      skills:{Couture:{level:1,xp:0},Croquis:{level:1,xp:0},Matières:{level:1,xp:0},Finitions:{level:1,xp:0},Patronage:{level:0,xp:0},Créativité:{level:1,xp:0}},
      knowledge:[],
      inspiration:[{id:'home-first-light',title:'Première lumière',source:'Chez toi',day:1,used:false,text:'La lumière de ton nouveau logement devient déjà une ambiance à retenir.'}],
      carnet:{pages:[{id:'depart',type:'journal',title:'Un nouveau départ',text:'Premier jour dans mon nouveau logement. Tout reste à construire.',createdDay:1}],discoveries:[],palettes:[],places:[],techniques:[],suppliers:[],contacts:[],creations:[],careerMemories:[{id:'career-start',day:1,title:'Le début',text:'Installation dans le premier logement et début de la carrière.'}]},
      agenda:{appointments:[],deadlines:[],trips:[],events:[]},
      contacts:[],
      missions:{available:clone(starterMissionTemplates),active:[],completed:[],failed:[]},
      orders:[],
      messages:[{id:'welcome',from:'Carnet',subject:'Bienvenue chez toi',body:'Installe-toi, regarde autour de toi et commence doucement.',day:1,read:false}],
      map:{discoveredPlaces:[],savedPlaces:[],realEstateAlerts:[],neighborhood:clone(neighborhoodSeeds)},
      progression:{tutorialStage:'arrived',unlocked:['carnet','agenda','matieres','carte','messages','missions','contacts','inspiration','portfolio','vie'],careerLevel:1},
      habits:{coffee:{name:'Prendre un café avant de travailler',streak:0,lastDay:0},walk:{name:'Sortir marcher pour observer',streak:0,lastDay:0},music:{name:'Mettre une ambiance musicale',streak:0,lastDay:0}},
      surprises:[],portfolio:[],storyArcs:[],rivals:[],mentors:[],trends:[{id:'soft-volume',name:'Volumes souples',season:'Automne',strength:2},{id:'natural-textures',name:'Matières naturelles',season:'Automne',strength:3}],
      collections:[],creations:[],team:[],finances:{income:[],expenses:[],rent:residence?.price||0}
    };
  }
  function migrate(s){if(!s)return s;const fresh=baseState({id:s.player?.characterId,name:s.player?.name},s.home?.current);const merge=(a,b)=>Object.assign(a,b||{});s.version=VERSION;s.player=merge(fresh.player,s.player);s.player.reputation=merge(fresh.player.reputation,s.player.reputation);s.world=merge(fresh.world,s.world);s.home=merge(fresh.home,s.home);s.map=merge(fresh.map,s.map);if(!s.home.memories)s.home.memories=[];if(!s.home.objects)s.home.objects=clone(fresh.home.objects);if(!s.inspiration)s.inspiration=[];if(!s.carnet)s.carnet=fresh.carnet;if(!s.carnet.careerMemories)s.carnet.careerMemories=[];if(!s.contacts)s.contacts=[];if(!s.habits)s.habits=fresh.habits;if(!s.surprises)s.surprises=[];if(!s.portfolio)s.portfolio=[];if(!s.storyArcs)s.storyArcs=[];if(!s.rivals)s.rivals=[];if(!s.mentors)s.mentors=[];if(!s.trends)s.trends=fresh.trends;if(!s.map.neighborhood)s.map.neighborhood=clone(neighborhoodSeeds);return s}
  function save(state){state=migrate(state);state.updatedAt=nowISO();localStorage.setItem(KEY,JSON.stringify(state));return state}
  function load(){try{const raw=localStorage.getItem(KEY);return raw?migrate(JSON.parse(raw)):null}catch(e){return null}}
  function ensure(character,residence){let s=load();if(!s)s=baseState(character,residence);if(character){s.player.characterId=character.id;s.player.name=character.name}if(residence&&!s.home.current){s.home.current=residence;s.home.properties=[residence];s.home.primaryResidenceId=residence.id;s.home.primaryAtelierId=residence.id;s.world.currentCity=residence.city;s.world.currentRegion=residence.region;s.world.currentDepartment=residence.department}s.started=true;return save(s)}
  function addCarnetPage(title,text,type='journal'){const s=load();if(!s)return null;s.carnet.pages.push({id:'page-'+Date.now(),type,title,text,createdDay:s.world.day});return save(s)}
  function addCareerMemory(title,text){const s=load();if(!s)return null;s.carnet.careerMemories.push({id:'memory-'+Date.now(),day:s.world.day,title,text});return save(s)}
  function addInspiration(title,text,source='Observation'){const s=load();if(!s)return null;s.inspiration.push({id:'insp-'+Date.now(),title,text,source,day:s.world.day,used:false});s.player.creativeFlow=clamp(s.player.creativeFlow+6,0,100);return save(s)}
  function addContact(contact){const s=load();if(!s)return null;let c=s.contacts.find(x=>x.id===contact.id);if(!c){c={relationship:0,status:'Nouveau contact',notes:[],metDay:s.world.day,lastInteractionDay:s.world.day,trust:0,referrals:0,...contact};s.contacts.push(c)}return save(s)}
  function touchContact(id,delta,note){const s=load();if(!s)return null;let c=s.contacts.find(x=>x.id===id);if(!c)return s;c.relationship=clamp((c.relationship||0)+delta,-100,100);c.trust=clamp((c.trust||0)+Math.max(-2,Math.round(delta/3)),0,100);c.lastInteractionDay=s.world.day;if(!c.metDay)c.metDay=s.world.day;if(note)c.notes.push({day:s.world.day,text:note});c.status=c.relationship>=40?'Relation fidèle':c.relationship>=25?'Relation de confiance':c.relationship>=10?'Bon contact':c.relationship<0?'Relation fragile':'Nouveau contact';return save(s)}
  function addInventory(item){const s=load();if(!s)return null;const found=s.inventory.find(i=>i.id===item.id);if(found)found.qty=(found.qty||0)+(item.qty||1);else s.inventory.push(item);return save(s)}
  function addSkillXp(skill,amount=1){const s=load();if(!s)return null;if(!s.skills[skill])s.skills[skill]={level:0,xp:0};s.skills[skill].xp+=amount;while(s.skills[skill].xp>=5){s.skills[skill].xp-=5;s.skills[skill].level+=1}return save(s)}
  function acceptMission(id){const s=load();if(!s)return null;const i=s.missions.available.findIndex(m=>m.id===id);if(i<0)return s;const m=s.missions.available.splice(i,1)[0];m.acceptedDay=s.world.day;m.deadlineDay=s.world.day+m.deadlineDays;m.progress=0;s.missions.active.push(m);s.agenda.deadlines.push({id:'deadline-'+m.id,title:m.title,day:m.deadlineDay,type:'mission'});let c=s.contacts.find(x=>x.id===m.clientId);if(!c){c=makeContactFromMission(m);c.metDay=s.world.day;c.lastInteractionDay=s.world.day;s.contacts.push(c)}c.notes.push({day:s.world.day,text:'Première commande acceptée : '+m.title});s.messages.push({id:'accepted-'+m.id,from:m.client,subject:'Commande confirmée',body:m.brief,day:s.world.day,read:false});s.carnet.pages.push({id:'mission-'+m.id,type:'commande',title:'Nouvelle commande : '+m.title,text:m.client+' — '+m.brief,createdDay:s.world.day});s.player.confidence=clamp(s.player.confidence+2,0,100);return save(s)}
  function progressMission(id,hours){const s=load();if(!s)return null;const m=s.missions.active.find(x=>x.id===id);if(!m)return s;const h=clamp(hours,1,4);m.progress=Math.min(m.durationHours,(m.progress||0)+h);s.world.hour+=h;s.player.energy=clamp(s.player.energy-h*7,0,100);s.player.stress=clamp(s.player.stress+(m.difficulty||1)*2,0,100);s.player.creativeFlow=clamp(s.player.creativeFlow+(s.player.mood==='Inspirée'?2:0)-1,0,100);while(s.world.hour>=24){s.world.hour-=24;s.world.day+=1}if(m.progress>=m.durationHours)return completeMission(id);return save(s)}
  function completeMission(id){const s=load();if(!s)return null;const i=s.missions.active.findIndex(m=>m.id===id);if(i<0)return s;const m=s.missions.active.splice(i,1)[0];m.completedDay=s.world.day;m.onTime=s.world.day<=m.deadlineDay;s.missions.completed.push(m);const genius=(s.player.creativeFlow>=70&&Math.random()<.18);m.breakthrough=genius;const money=m.rewards.money||0;s.player.money+=money;s.finances.income.push({day:s.world.day,amount:money,label:m.title});if(m.rewards.reputationLocal)s.player.reputation.local+=m.rewards.reputationLocal;if(m.rewards.reputationCreative)s.player.reputation.creative+=m.rewards.reputationCreative;if(genius)s.player.reputation.creative+=2;if(!m.onTime)s.player.reputation.local=Math.max(0,s.player.reputation.local-1);let c=s.contacts.find(x=>x.id===m.clientId);if(!c){c=makeContactFromMission(m);s.contacts.push(c)}c.relationship=clamp((c.relationship||0)+(m.onTime?(m.rewards.relationship||5):-5),-100,100);c.trust=clamp((c.trust||0)+(m.onTime?3:-2),0,100);c.lastInteractionDay=s.world.day;c.status=c.relationship>=40?'Relation fidèle':c.relationship>=25?'Relation de confiance':c.relationship>=10?'Bon contact':c.relationship<0?'Relation fragile':'Nouveau contact';c.notes.push({day:s.world.day,text:m.onTime?'Commande livrée dans les temps.':'Commande terminée en retard.'});const creation={id:'creation-'+m.id,title:m.title,day:s.world.day,type:m.kind,client:m.client,breakthrough:genius,location:s.world.currentCity};s.carnet.creations.push(creation);s.portfolio.push({...creation,brief:m.brief,budget:m.budget});s.carnet.careerMemories.push({id:'memory-'+m.id,day:s.world.day,title:genius?'Une création marquante':'Commande terminée',text:m.title+' pour '+m.client+'.'});if(m.inspiration)s.inspiration.push({id:'insp-'+m.id,title:m.inspiration,source:m.client,day:s.world.day,used:false,text:'Une idée née pendant '+m.title+'.'});if(m.rewards.skill){if(!s.skills[m.rewards.skill])s.skills[m.rewards.skill]={level:0,xp:0};s.skills[m.rewards.skill].xp+=m.rewards.skillXp||1;while(s.skills[m.rewards.skill].xp>=5){s.skills[m.rewards.skill].xp-=5;s.skills[m.rewards.skill].level+=1}}s.agenda.deadlines=s.agenda.deadlines.filter(d=>d.id!=='deadline-'+m.id);s.player.confidence=clamp(s.player.confidence+(m.onTime?6:-2)+(genius?8:0),0,100);s.player.mood=genius?'Euphorique':m.onTime?'Fière':'Soulagée';s.messages.push({id:'done-'+m.id,from:m.client,subject:genius?'C’est magnifique !':m.onTime?'Merci !':'Commande reçue',body:genius?'Cette pièce dépasse ce que j’imaginais. Je vais parler de toi autour de moi.':m.onTime?'La commande est terminée. Votre relation se renforce.':'La commande est terminée, mais le retard a laissé une impression mitigée.',day:s.world.day,read:false});if(genius){c.referrals=(c.referrals||0)+1;s.messages.push({id:'ref-'+m.id,from:'Réseau',subject:'Une recommandation se prépare',body:m.client+' a parlé de ton travail à une connaissance.',day:s.world.day,read:false});}return save(s)}
  function failExpiredMissions(s){const expired=s.missions.active.filter(m=>s.world.day>m.deadlineDay+1);expired.forEach(m=>{s.missions.active=s.missions.active.filter(x=>x.id!==m.id);m.failedDay=s.world.day;s.missions.failed.push(m);s.agenda.deadlines=s.agenda.deadlines.filter(d=>d.id!=='deadline-'+m.id);s.player.reputation.local=Math.max(0,s.player.reputation.local-2);s.player.confidence=clamp(s.player.confidence-6,0,100);let c=s.contacts.find(x=>x.id===m.clientId);if(!c){c=makeContactFromMission(m);s.contacts.push(c)}c.relationship=clamp((c.relationship||0)-12,-100,100);c.status='Relation fragile';c.notes.push({day:s.world.day,text:'Commande abandonnée après dépassement du délai.'});s.messages.push({id:'failed-'+m.id,from:m.client,subject:'Commande annulée',body:'Le délai est dépassé. La commande est perdue et la relation se dégrade.',day:s.world.day,read:false});});}
  function updateMood(s){if(s.player.energy<25)s.player.mood='Épuisée';else if(s.player.stress>70)s.player.mood='Sous pression';else if(s.player.creativeFlow>65)s.player.mood='Inspirée';else if(s.player.confidence>65)s.player.mood='Confiance';else s.player.mood='Curieuse';}
  function generateSurprise(s){if(Math.random()>.35)return;const base=clone(surprisePool[(s.world.day+s.world.currentCity?.length||0)%surprisePool.length]);base.id='surprise-'+s.world.day+'-'+Date.now();base.day=s.world.day;s.surprises.unshift(base);s.messages.push({id:base.id,from:'Chez toi',subject:base.title,body:base.text,day:s.world.day,read:false});if(base.effect==='inspiration')s.inspiration.push({id:'insp-'+base.id,title:base.title,source:'Quotidien',day:s.world.day,used:false,text:base.text});if(base.effect==='stress')s.player.stress=clamp(s.player.stress+6,0,100);}
  function finishDay(){const s=load();if(!s)return null;s.world.day+=1;s.world.hour=8;s.player.energy=clamp(s.player.energy+35,0,100);s.player.stress=clamp(s.player.stress-10,0,100);s.player.creativeFlow=clamp(s.player.creativeFlow-2,0,100);failExpiredMissions(s);generateSurprise(s);updateMood(s);const urgent=s.missions.active.filter(m=>m.deadlineDay-s.world.day<=1);if(urgent.length)s.messages.push({id:'urgent-'+s.world.day,from:'Agenda',subject:'Échéance proche',body:urgent.map(m=>m.title).join(', ')+' demande ton attention.',day:s.world.day,read:false});else s.messages.push({id:'day-'+s.world.day,from:'Agenda',subject:'Jour '+s.world.day,body:'Une nouvelle journée commence.',day:s.world.day,read:false});return save(s)}
  function doHabit(id){const s=load();if(!s||!s.habits[id])return s;const h=s.habits[id];if(h.lastDay===s.world.day)return s;h.streak=(h.lastDay===s.world.day-1)?h.streak+1:1;h.lastDay=s.world.day;if(id==='coffee'){s.player.energy=clamp(s.player.energy+8,0,100);s.player.stress=clamp(s.player.stress-3,0,100)}if(id==='walk'){s.player.creativeFlow=clamp(s.player.creativeFlow+10,0,100);s.inspiration.push({id:'walk-'+s.world.day,title:'Détail aperçu en marchant',source:'Quartier',day:s.world.day,used:false,text:'Une couleur, un geste ou une silhouette repérée dehors.'})}if(id==='music'){s.player.stress=clamp(s.player.stress-8,0,100);s.player.creativeFlow=clamp(s.player.creativeFlow+4,0,100)}updateMood(s);return save(s)}
  function observeHome(){const s=load();if(!s)return null;const city=s.world.currentCity||'ton quartier';const season=s.world.season||'la saison';const texts=['La lumière découpe une nouvelle forme sur le mur.','Un reflet sur la vitre crée une palette douce.','Un détail de matière dans la pièce donne une idée de texture.','Le dehors et le calme de la pièce se répondent.'];const text=texts[(s.world.day+(city.length||0))%texts.length]+' '+city+', '+season.toLowerCase()+'.';s.inspiration.push({id:'obs-'+Date.now(),title:'Observation depuis chez toi',source:'Fenêtre',day:s.world.day,used:false,text});s.player.creativeFlow=clamp(s.player.creativeFlow+5,0,100);updateMood(s);return save(s)}
  function interactNeighborhood(kind){const s=load();if(!s)return null;const place=s.map.neighborhood.find(x=>x.kind===kind);if(!place)return s;if(kind==='cafe'){s.player.stress=clamp(s.player.stress-8,0,100);s.player.energy=clamp(s.player.energy+4,0,100)}if(kind==='mercerie'){s.inventory.push({id:'sample-'+Date.now(),type:'fabric',name:'Échantillon trouvé en mercerie',qty:1,unit:'coupon',quality:1,memory:'Trouvé dans '+(s.world.currentCity||'le quartier')+'.'})}if(kind==='marche'||kind==='promenade'){s.inspiration.push({id:'place-'+Date.now(),title:place.name,source:'Quartier',day:s.world.day,used:false,text:place.text});s.player.creativeFlow=clamp(s.player.creativeFlow+7,0,100)}s.world.hour+=1;updateMood(s);return save(s)}
  function moveHome(residence){const s=load();if(!s)return null;const previous=s.home.current;s.home.current=residence;if(!s.home.properties.find(p=>p.id===residence.id))s.home.properties.push(residence);s.home.primaryResidenceId=residence.id;s.home.primaryAtelierId=residence.id;s.world.currentCity=residence.city;s.world.currentRegion=residence.region;s.world.currentDepartment=residence.department;s.home.memories.push({id:'move-'+Date.now(),day:s.world.day,title:'Déménagement',text:(previous?previous.city+' → ':'')+residence.city});s.carnet.careerMemories.push({id:'move-career-'+Date.now(),day:s.world.day,title:'Nouveau lieu de vie',text:'Installation à '+residence.city+', dans '+residence.type+'.'});s.carnet.pages.push({id:'last-night-'+Date.now(),type:'journal',title:'Dernier soir dans un lieu',text:previous?'Quelques souvenirs restent liés à '+previous.city+'.':'Un nouveau chapitre commence.',createdDay:s.world.day});return save(s)}
  function reset(){localStorage.removeItem(KEY)}
  window.HauteCoutureCore={KEY,VERSION,baseState,load,save,ensure,reset,addCarnetPage,addCareerMemory,addInspiration,addContact,touchContact,addInventory,addSkillXp,acceptMission,progressMission,completeMission,finishDay,moveHome,doHabit,observeHome,interactNeighborhood,starterMissionTemplates};
})();
