/* Haute Couture Live — moteur central de partie. Temps de jeu, jamais temps réel. */
(function(){
const STORAGE_KEY='haute-couture-game-state-v1',VERSION=2;
const clone=o=>JSON.parse(JSON.stringify(o)),uid=p=>(p||'id')+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);
const safeJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch(e){return fallback}};
const saveRaw=s=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('hc-game-state',{detail:clone(s)}));return s};
const isoLocal=d=>{const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}:00`};
function initialClock(){const d=new Date();d.setHours(9,0,0,0);return{iso:isoLocal(d),totalMinutes:0,day:1}}
function startPath(){return safeJSON('haute-couture-start-path-v1',{type:'career'})||{type:'career'}}
function initialState(){const homeSave=safeJSON('haute-couture-home',{}),home=homeSave.home||safeJSON('haute-couture-residence',null),legacyBank=safeJSON('haute-couture-bank',{}),legacyStats=safeJSON('haute-couture-player-stats',{}),path=startPath(),school=safeJSON('haute-couture-school-choice-v1',null),starting=Number.isFinite(Number(legacyBank.balance))?Number(legacyBank.balance):Number(homeSave.startingBudget||0),city=path.type==='school'?(school?.city||path.city||home?.city||'France'):(homeSave.city||home?.city||'France');const s={version:VERSION,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),clock:initialClock(),path:{type:path.type||'career',schoolId:school?.id||path.schoolId||null},player:{name:'Marion',money:starting,reputation:Number(legacyStats.reputation||0),level:1,city},home:{listingId:home?.id||null,city,type:home?.title||'Mon logement',address:home?.address||city,rent:Number(home?.price||0)+Number(home?.charges||0)},objectives:[],messages:[],calendar:[],missions:[],relationships:{},inventory:[],portfolio:[],transactions:[],flags:{introBootstrapped:false,visitedLocations:[]},reputationTracks:{local:0,professional:0,creative:0,prestige:0,clientele:0,mariage:0,scene:0,luxe:0}};bootstrap(s);return s}
function purgeLegacyInes(s){s.player=s.player||{};s.player.name='Marion';s.messages=(s.messages||[]).filter(m=>m.id!=='msg-ines-intro'&&String(m.from||'').toLowerCase()!=='inès'&&String(m.from||'').toLowerCase()!=='ines');s.missions=(s.missions||[]).filter(m=>m.id!=='mission-ines-robe'&&String(m.client||'').toLowerCase()!=='inès'&&String(m.client||'').toLowerCase()!=='ines');if(s.relationships){delete s.relationships.Inès;delete s.relationships.Ines}return s}
function bootstrap(s){s.flags=s.flags||{};s.flags.visitedLocations=s.flags.visitedLocations||[];purgeLegacyInes(s);if(s.flags.introBootstrapped)return s;s.flags.introBootstrapped=true;const now=s.clock.iso,path=s.path?.type||startPath().type;if(path==='school'){const school=safeJSON('haute-couture-school-choice-v1',null);s.objectives.push({id:'school-first-day',title:'Commencer ma première journée de cours',status:'active',category:'ecole'},{id:'school-campus',title:'Découvrir progressivement mon école',status:'active',category:'ecole'});s.messages.push({id:'msg-school-welcome',from:'Scolarité',avatar:'E',subject:'Bienvenue Marion',text:`Bienvenue Marion${school?.name?' à '+school.name:''}. Ton emploi du temps, tes cours et tes premiers travaux t’attendent. Avance à ton rythme : aucune journée ne passe sans ton action.`,receivedAt:now,read:false});return s}s.objectives.push({id:'intro-phone',title:'Regarder mon téléphone',status:'active',category:'decouverte'},{id:'intro-look',title:'Préparer mon premier look',status:'active',category:'dressing'},{id:'intro-city',title:`Découvrir ${s.player.city}`,status:'active',category:'ville'});s.messages.push({id:'msg-agence-intro',from:'Réseau professionnel local',avatar:'A',subject:'Premiers contacts',text:`Bienvenue Marion. Les premières opportunités professionnelles apparaîtront à ${s.player.city} au fil de tes rencontres, de ton travail et de ta réputation.`,receivedAt:now,read:false});return s}
function load(){let s=safeJSON(STORAGE_KEY,null);if(!s||s.version!==VERSION)s=initialState();s.updatedAt=new Date().toISOString();purgeLegacyInes(s);bootstrap(s);saveRaw(s);return s}
function save(s){s.updatedAt=new Date().toISOString();purgeLegacyInes(s);return saveRaw(s)}
function get(){return load()} function mutate(fn){const s=load();fn(s);return save(s)}
function gameDate(s){return new Date((s||load()).clock.iso)}
function formatDateTime(s,withTime=true){const d=gameDate(s);return new Intl.DateTimeFormat('fr-FR',withTime?{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}:{weekday:'short',day:'2-digit',month:'2-digit'}).format(d)}
function formatTime(iso){return new Intl.DateTimeFormat('fr-FR',{hour:'2-digit',minute:'2-digit'}).format(new Date(iso))}
function advanceTime(minutes,reason){minutes=Math.max(0,Number(minutes)||0);return mutate(s=>{const before=new Date(s.clock.iso),d=new Date(before.getTime()+minutes*60000),beforeDay=before.toDateString();s.clock.iso=isoLocal(d);s.clock.totalMinutes=(s.clock.totalMinutes||0)+minutes;if(d.toDateString()!==beforeDay)s.clock.day=(s.clock.day||1)+1;if(reason)s.calendar.push({id:uid('time'),title:reason,type:'activity',start:isoLocal(before),end:isoLocal(d),status:'done'})})}
function endDay({wakeHour=9}={}){return mutate(s=>{const before=new Date(s.clock.iso),next=new Date(before);next.setDate(next.getDate()+1);next.setHours(wakeHour,0,0,0);s.calendar.push({id:uid('sleep'),title:'Fin de journée',type:'rest',start:isoLocal(before),end:isoLocal(next),status:'done'});s.clock.iso=isoLocal(next);s.clock.day=(s.clock.day||1)+1;s.clock.totalMinutes=(s.clock.totalMinutes||0)+Math.max(0,Math.round((next-before)/60000));const now=next.getTime();s.calendar.forEach(e=>{if(e.status==='planned'&&e.type!=='deadline'&&new Date(e.start).getTime()<now)e.status='missed'});s.missions.forEach(m=>{if(m.status==='accepted'&&m.deadline&&new Date(m.deadline).getTime()<now)m.late=true})})}
function transact(amount,label,category='misc'){amount=Number(amount)||0;return mutate(s=>{s.player.money+=amount;s.transactions.unshift({id:uid('tx'),amount,label,category,at:s.clock.iso});localStorage.setItem('haute-couture-bank',JSON.stringify({balance:s.player.money,updatedAt:new Date().toISOString()}))})}
function addReputation(amount,track='professional',reason=''){amount=Number(amount)||0;return mutate(s=>{s.player.reputation+=amount;s.reputationTracks[track]=(s.reputationTracks[track]||0)+amount;if(reason)s.calendar.push({id:uid('rep'),title:reason,type:'reputation',start:s.clock.iso,status:'done'});localStorage.setItem('haute-couture-player-stats',JSON.stringify({reputation:s.player.reputation}))})}
function completeObjective(id){return mutate(s=>{const o=s.objectives.find(x=>x.id===id);if(o)o.status='done'})}
function markMessageRead(id){return mutate(s=>{const m=s.messages.find(x=>x.id===id);if(m)m.read=true})}
function addMessage(msg){return mutate(s=>s.messages.unshift({id:msg.id||uid('msg'),from:msg.from||'Contact',avatar:msg.avatar||'•',subject:msg.subject||'',text:msg.text||'',receivedAt:s.clock.iso,read:false,action:msg.action||null}))}
function schedule(evt){return mutate(s=>s.calendar.push({id:evt.id||uid('evt'),title:evt.title||'Événement',type:evt.type||'event',start:evt.start||s.clock.iso,end:evt.end||null,status:evt.status||'planned',location:evt.location||null,missionId:evt.missionId||null}))}
function registerVisit(place){place=String(place||'').trim();if(!place)return;const out=mutate(s=>{s.flags=s.flags||{};s.flags.visitedLocations=s.flags.visitedLocations||[];if(!s.flags.visitedLocations.includes(place))s.flags.visitedLocations.push(place)});window.dispatchEvent(new CustomEvent('hc-travel-visited',{detail:{place}}));return out}
function offerFirstMission(){return{ok:false,reason:'legacy-character-removed'}}
function acceptMission(id){return mutate(s=>{const m=s.missions.find(x=>x.id===id);if(!m)return;m.status='accepted';const d=new Date(s.clock.iso);d.setDate(d.getDate()+2);d.setHours(19,0,0,0);m.deadline=isoLocal(d);if(!s.calendar.some(e=>e.id==='deadline-'+id))s.calendar.push({id:'deadline-'+id,title:'Deadline — '+m.title,type:'deadline',start:m.deadline,status:'planned',missionId:id})})}
function completeMission(id){return mutate(s=>{const m=s.missions.find(x=>x.id===id);if(!m||m.status==='completed')return;m.status='completed';m.completedAt=s.clock.iso;s.player.money+=Number(m.reward||0);s.player.reputation+=2;s.reputationTracks.professional=(s.reputationTracks.professional||0)+2;s.reputationTracks.clientele=(s.reputationTracks.clientele||0)+1;s.transactions.unshift({id:uid('tx'),amount:Number(m.reward||0),label:m.title,category:'mission',at:s.clock.iso});s.portfolio.push({id:uid('portfolio'),name:m.title,client:m.client,type:m.type,date:s.clock.iso,notable:false});if(s.relationships[m.client]){s.relationships[m.client].trust+=5;s.relationships[m.client].affinity+=2;s.relationships[m.client].history.push('Mission réussie : '+m.title)}localStorage.setItem('haute-couture-bank',JSON.stringify({balance:s.player.money,updatedAt:new Date().toISOString()}));localStorage.setItem('haute-couture-player-stats',JSON.stringify({reputation:s.player.reputation}))})}
function nextEvent(s){s=s||load();const now=new Date(s.clock.iso).getTime();return s.calendar.filter(e=>e.status==='planned'&&new Date(e.start).getTime()>=now).sort((a,b)=>new Date(a.start)-new Date(b.start))[0]||null}
function unreadCount(s){return(s||load()).messages.filter(m=>!m.read).length}
window.HCGame={get,save,mutate,advanceTime,endDay,transact,addReputation,completeObjective,markMessageRead,addMessage,schedule,registerVisit,offerFirstMission,acceptMission,completeMission,nextEvent,unreadCount,formatDateTime,formatTime,storageKey:STORAGE_KEY};
document.addEventListener('click',e=>{const el=e.target.closest&&e.target.closest('[data-action="atelier"],[data-action="telephone"],[data-action="agenda"],[data-action="sortir"]');if(!el||!location.pathname.includes('/chez-moi/'))return;const action=el.getAttribute('data-action');if(!['atelier','telephone','agenda','sortir'].includes(action))return;e.preventDefault();e.stopImmediatePropagation();location.href=action==='atelier'?'../atelier/':action==='telephone'?'../telephone/':action==='agenda'?'../agenda/':'../ville/'},true);
const addScript=(src,tag,onload)=>{if(document.querySelector(`script[${tag}]`)){onload&&onload();return}const s=document.createElement('script');s.src=src;s.defer=true;s.setAttribute(tag,'1');s.onload=()=>onload&&onload();s.onerror=()=>console.warn('[HCGame] failed to load '+src);document.head.appendChild(s)};
const engineScript=[...document.scripts].find(s=>/\/game-engine\.js(?:\?|$)/.test(s.src));const hcLiveBase=engineScript?new URL('.',engineScript.src).href:(location.pathname.includes('/hc-live/')?location.pathname.split('/hc-live/')[0]+'/hc-live/':'/');
addScript(hcLiveBase+'career-opportunities-v1.js?v=20260903-career3','data-hc-career-opportunities');
if(location.pathname.includes('/chez-moi/')){addScript('./real-home-visual-v1.js?v=20260825-realhome1','data-hc-real-home-visual');addScript('./creations-access-v1.js?v=20260903-career2','data-hc-home-creations-access')}
if(location.pathname.includes('/telephone/')){const loadDynamics=()=>addScript('./phone-social-dynamics.js?v=20260824-social-dyn2','data-hc-social-dynamics');if(window.HCPhone)loadDynamics();else addScript('./phone-gameplay-engine.js?v=20260824-phone-core3','data-hc-phone-core',loadDynamics)}
if(location.pathname.includes('/agenda/'))addScript('./nimes-event-flow-v1.js?v=20260825-agenda-events1','data-hc-nimes-agenda-events');
if(location.pathname.includes('/ville/')){if(window.L&&typeof window.L.map==='function'&&!window.__HC_LEAFLET_CAPTURED){window.__HC_LEAFLET_CAPTURED=true;const originalMap=window.L.map;window.L.map=function(){const m=originalMap.apply(this,arguments);window.HCLeafletMap=m;window.dispatchEvent(new CustomEvent('hc-map-ready',{detail:{map:m}}));return m}}addScript('../travel/france/cities/nimes-rich-content.js?v=20260824-rich2','data-hc-nimes-rich',()=>addScript('./rich-place-ui.js?v=20260825-living-map-v3','data-hc-rich-place-ui'))}
})();