(function(){
  const KEY='haute-couture-game-state-v1';
  const VERSION=2;
  const clone=o=>JSON.parse(JSON.stringify(o));
  const nowISO=()=>new Date().toISOString();
  const starterInventory=[
    {id:'machine-basic',type:'equipment',name:'Machine à coudre familiale',qty:1,quality:1,memory:'Ta toute première machine.'},
    {id:'scissors-basic',type:'equipment',name:'Ciseaux de couture',qty:1,quality:1},
    {id:'needles-basic',type:'haberdashery',name:'Aiguilles assorties',qty:1,quality:1},
    {id:'thread-neutral',type:'haberdashery',name:'Fils neutres',qty:4,quality:1},
    {id:'fabric-cotton-cream',type:'fabric',name:'Coton écru',qty:2,unit:'m',quality:1}
  ];
  const starterMissionTemplates=[
    {id:'retouche-voisine',kind:'retouche',title:'Une première retouche',clientId:'lucie-voisine',client:'Lucie, ta voisine',relationshipKind:'voisinage',brief:'Raccourcir et reprendre une robe simple pour qu’elle tombe mieux.',budget:55,durationHours:4,difficulty:1,deadlineDays:3,inspiration:'Gestes simples et précision du quotidien',rewards:{money:55,reputationLocal:2,relationship:8,skill:'Couture',skillXp:2}},
    {id:'jupe-simple',kind:'commande',title:'Une jupe pour un dîner',clientId:'emma-cliente',client:'Emma, première cliente',relationshipKind:'cliente',brief:'Créer une jupe simple, portable et bien finie à partir d’un tissu accessible.',budget:95,durationHours:7,difficulty:1,deadlineDays:5,inspiration:'Silhouette de soirée sobre et mouvement',rewards:{money:95,reputationLocal:3,relationship:10,skill:'Finitions',skillXp:2}},
    {id:'transformation-vintage',kind:'upcycling',title:'Transformer une pièce ancienne',clientId:'nora-passage',client:'Nora, cliente de passage',relationshipKind:'cliente',brief:'Donner une nouvelle vie à un vêtement ancien sans perdre son caractère.',budget:80,durationHours:6,difficulty:1,deadlineDays:4,inspiration:'Patine, mémoire textile et transformation',rewards:{money:80,reputationCreative:2,relationship:7,skill:'Créativité',skillXp:2}}
  ];
  function makeContactFromMission(m){return{id:m.clientId,name:m.client,kind:m.relationshipKind||'contact',relationship:0,status:'Nouveau contact',notes:[],metDay:null,lastInteractionDay:null};}
  function baseState(character,residence){
    return {
      version:VERSION,createdAt:nowISO(),updatedAt:nowISO(),started:false,
      player:{characterId:character?.id||null,name:character?.name||'',money:1200,energy:100,stress:10,reputation:{local:0,professional:0,creative:0,prestige:0,clientele:0}},
      world:{day:1,hour:9,minute:0,season:'Automne',weather:'Doux',currentCity:residence?.city||null,currentRegion:residence?.region||null,currentDepartment:residence?.department||null},
      home:{current:residence||null,properties:residence?[residence]:[],primaryResidenceId:residence?.id||null,primaryAtelierId:residence?.id||null,decor:[],equipmentSlots:[],storageBonus:0,memories:[{id:'movein',day:1,title:'Premier emménagement',text:'Quelques cartons, une machine et beaucoup d’idées.'}]},
      inventory:clone(starterInventory),
      skills:{Couture:{level:1,xp:0},Croquis:{level:1,xp:0},Matières:{level:1,xp:0},Finitions:{level:1,xp:0},Patronage:{level:0,xp:0},Créativité:{level:1,xp:0}},
      knowledge:[],
      inspiration:[{id:'home-first-light',title:'Première lumière',source:'Chez toi',day:1,used:false,text:'La lumière de ton nouveau logement devient déjà une ambiance à retenir.'}],
      carnet:{pages:[{id:'depart',type:'journal',title:'Un nouveau départ',text:'Premier jour dans mon nouveau logement. Tout reste à construire.',createdDay:1}],discoveries:[],palettes:[],places:[],techniques:[],suppliers:[],contacts:[],creations:[],careerMemories:[{id:'career-start',day:1,title:'Le début',text:'Installation dans le premier logement et début de la carrière.'}]},
      agenda:{appointments:[],deadlines:[],trips:[],events:[]},
      contacts:[],
      missions:{available:clone(starterMissionTemplates),active:[],completed:[],failed:[]},
      orders:[],
      messages:[{id:'welcome',from:'Carnet',subject:'Bienvenue chez toi',body:'Installe-toi, regarde autour de toi et commence doucement.',day:1,read:false}],
      map:{discoveredPlaces:[],savedPlaces:[],realEstateAlerts:[]},
      progression:{tutorialStage:'arrived',unlocked:['carnet','agenda','matieres','carte','messages','missions','contacts','inspiration'],careerLevel:1},
      collections:[],creations:[],team:[],finances:{income:[],expenses:[],rent:residence?.price||0}
    };
  }
  function migrate(s){if(!s)return s;if(!s.inspiration)s.inspiration=[];if(!s.home.memories)s.home.memories=[];if(!s.carnet.careerMemories)s.carnet.careerMemories=[];if(!s.contacts)s.contacts=[];s.version=VERSION;return s}
  function save(state){state=migrate(state);state.updatedAt=nowISO();localStorage.setItem(KEY,JSON.stringify(state));return state}
  function load(){try{const raw=localStorage.getItem(KEY);return raw?migrate(JSON.parse(raw)):null}catch(e){return null}}
  function ensure(character,residence){let s=load();if(!s)s=baseState(character,residence);if(character){s.player.characterId=character.id;s.player.name=character.name}if(residence&&!s.home.current){s.home.current=residence;s.home.properties=[residence];s.home.primaryResidenceId=residence.id;s.home.primaryAtelierId=residence.id;s.world.currentCity=residence.city;s.world.currentRegion=residence.region;s.world.currentDepartment=residence.department}s.started=true;return save(s)}
  function addCarnetPage(title,text,type='journal'){const s=load();if(!s)return null;s.carnet.pages.push({id:'page-'+Date.now(),type,title,text,createdDay:s.world.day});return save(s)}
  function addCareerMemory(title,text){const s=load();if(!s)return null;s.carnet.careerMemories.push({id:'memory-'+Date.now(),day:s.world.day,title,text});return save(s)}
  function addInspiration(title,text,source='Observation'){const s=load();if(!s)return null;s.inspiration.push({id:'insp-'+Date.now(),title,text,source,day:s.world.day,used:false});return save(s)}
  function addContact(contact){const s=load();if(!s)return null;let c=s.contacts.find(x=>x.id===contact.id);if(!c){c={relationship:0,status:'Nouveau contact',notes:[],metDay:s.world.day,lastInteractionDay:s.world.day,...contact};s.contacts.push(c)}return save(s)}
  function touchContact(id,delta,note){const s=load();if(!s)return null;let c=s.contacts.find(x=>x.id===id);if(!c)return s;c.relationship=Math.max(-100,Math.min(100,(c.relationship||0)+delta));c.lastInteractionDay=s.world.day;if(!c.metDay)c.metDay=s.world.day;if(note)c.notes.push({day:s.world.day,text:note});c.status=c.relationship>=25?'Relation de confiance':c.relationship>=10?'Bon contact':c.relationship<0?'Relation fragile':'Nouveau contact';return save(s)}
  function addInventory(item){const s=load();if(!s)return null;const found=s.inventory.find(i=>i.id===item.id);if(found)found.qty=(found.qty||0)+(item.qty||1);else s.inventory.push(item);return save(s)}
  function addSkillXp(skill,amount=1){const s=load();if(!s)return null;if(!s.skills[skill])s.skills[skill]={level:0,xp:0};s.skills[skill].xp+=amount;while(s.skills[skill].xp>=5){s.skills[skill].xp-=5;s.skills[skill].level+=1}return save(s)}
  function acceptMission(id){const s=load();if(!s)return null;const i=s.missions.available.findIndex(m=>m.id===id);if(i<0)return s;const m=s.missions.available.splice(i,1)[0];m.acceptedDay=s.world.day;m.deadlineDay=s.world.day+m.deadlineDays;m.progress=0;s.missions.active.push(m);s.agenda.deadlines.push({id:'deadline-'+m.id,title:m.title,day:m.deadlineDay,type:'mission'});let c=s.contacts.find(x=>x.id===m.clientId);if(!c){c=makeContactFromMission(m);c.metDay=s.world.day;c.lastInteractionDay=s.world.day;s.contacts.push(c)}c.notes.push({day:s.world.day,text:'Première commande acceptée : '+m.title});s.messages.push({id:'accepted-'+m.id,from:m.client,subject:'Commande confirmée',body:m.brief,day:s.world.day,read:false});s.carnet.pages.push({id:'mission-'+m.id,type:'commande',title:'Nouvelle commande : '+m.title,text:m.client+' — '+m.brief,createdDay:s.world.day});return save(s)}
  function progressMission(id,hours){const s=load();if(!s)return null;const m=s.missions.active.find(x=>x.id===id);if(!m)return s;const h=Math.max(1,Math.min(hours,4));m.progress=Math.min(m.durationHours,(m.progress||0)+h);s.world.hour+=h;s.player.energy=Math.max(0,s.player.energy-h*7);s.player.stress=Math.min(100,s.player.stress+(m.difficulty||1)*2);while(s.world.hour>=24){s.world.hour-=24;s.world.day+=1}if(m.progress>=m.durationHours)return completeMission(id);return save(s)}
  function completeMission(id){const s=load();if(!s)return null;const i=s.missions.active.findIndex(m=>m.id===id);if(i<0)return s;const m=s.missions.active.splice(i,1)[0];m.completedDay=s.world.day;m.onTime=s.world.day<=m.deadlineDay;s.missions.completed.push(m);const money=m.rewards.money||0;s.player.money+=money;s.finances.income.push({day:s.world.day,amount:money,label:m.title});if(m.rewards.reputationLocal)s.player.reputation.local+=m.rewards.reputationLocal;if(m.rewards.reputationCreative)s.player.reputation.creative+=m.rewards.reputationCreative;if(!m.onTime){s.player.reputation.local=Math.max(0,s.player.reputation.local-1)}let c=s.contacts.find(x=>x.id===m.clientId);if(!c){c=makeContactFromMission(m);s.contacts.push(c)}c.relationship=Math.max(-100,Math.min(100,(c.relationship||0)+(m.onTime?(m.rewards.relationship||5):-5)));c.lastInteractionDay=s.world.day;c.status=c.relationship>=25?'Relation de confiance':c.relationship>=10?'Bon contact':c.relationship<0?'Relation fragile':'Nouveau contact';c.notes.push({day:s.world.day,text:m.onTime?'Commande livrée dans les temps.':'Commande terminée en retard.'});s.carnet.creations.push({id:'creation-'+m.id,title:m.title,day:s.world.day,type:m.kind,client:m.client});s.carnet.careerMemories.push({id:'memory-'+m.id,day:s.world.day,title:'Commande terminée',text:m.title+' pour '+m.client+'.'});if(m.inspiration)s.inspiration.push({id:'insp-'+m.id,title:m.inspiration,source:m.client,day:s.world.day,used:false,text:'Une idée née pendant '+m.title+'.'});if(m.rewards.skill){if(!s.skills[m.rewards.skill])s.skills[m.rewards.skill]={level:0,xp:0};s.skills[m.rewards.skill].xp+=m.rewards.skillXp||1;while(s.skills[m.rewards.skill].xp>=5){s.skills[m.rewards.skill].xp-=5;s.skills[m.rewards.skill].level+=1}}s.agenda.deadlines=s.agenda.deadlines.filter(d=>d.id!=='deadline-'+m.id);s.messages.push({id:'done-'+m.id,from:m.client,subject:m.onTime?'Merci !':'Commande reçue',body:m.onTime?'La commande est terminée. Votre relation se renforce.':'La commande est terminée, mais le retard a laissé une impression mitigée.',day:s.world.day,read:false});return save(s)}
  function failExpiredMissions(s){const expired=s.missions.active.filter(m=>s.world.day>m.deadlineDay+1);expired.forEach(m=>{s.missions.active=s.missions.active.filter(x=>x.id!==m.id);m.failedDay=s.world.day;s.missions.failed.push(m);s.agenda.deadlines=s.agenda.deadlines.filter(d=>d.id!=='deadline-'+m.id);s.player.reputation.local=Math.max(0,s.player.reputation.local-2);let c=s.contacts.find(x=>x.id===m.clientId);if(!c){c=makeContactFromMission(m);s.contacts.push(c)}c.relationship=Math.max(-100,(c.relationship||0)-12);c.status='Relation fragile';c.notes.push({day:s.world.day,text:'Commande abandonnée après dépassement du délai.'});s.messages.push({id:'failed-'+m.id,from:m.client,subject:'Commande annulée',body:'Le délai est dépassé. La commande est perdue et la relation se dégrade.',day:s.world.day,read:false});});}
  function finishDay(){const s=load();if(!s)return null;s.world.day+=1;s.world.hour=8;s.player.energy=Math.min(100,s.player.energy+35);s.player.stress=Math.max(0,s.player.stress-10);failExpiredMissions(s);const urgent=s.missions.active.filter(m=>m.deadlineDay-s.world.day<=1);if(urgent.length)s.messages.push({id:'urgent-'+s.world.day,from:'Agenda',subject:'Échéance proche',body:urgent.map(m=>m.title).join(', ')+' demande ton attention.',day:s.world.day,read:false});else s.messages.push({id:'day-'+s.world.day,from:'Agenda',subject:'Jour '+s.world.day,body:'Une nouvelle journée commence.',day:s.world.day,read:false});return save(s)}
  function moveHome(residence){const s=load();if(!s)return null;const previous=s.home.current;s.home.current=residence;if(!s.home.properties.find(p=>p.id===residence.id))s.home.properties.push(residence);s.home.primaryResidenceId=residence.id;s.home.primaryAtelierId=residence.id;s.world.currentCity=residence.city;s.world.currentRegion=residence.region;s.world.currentDepartment=residence.department;s.home.memories.push({id:'move-'+Date.now(),day:s.world.day,title:'Déménagement',text:(previous?previous.city+' → ':'')+residence.city});s.carnet.careerMemories.push({id:'move-career-'+Date.now(),day:s.world.day,title:'Nouveau lieu de vie',text:'Installation à '+residence.city+', dans '+residence.type+'.'});return save(s)}
  function reset(){localStorage.removeItem(KEY)}
  window.HauteCoutureCore={KEY,VERSION,baseState,load,save,ensure,reset,addCarnetPage,addCareerMemory,addInspiration,addContact,touchContact,addInventory,addSkillXp,acceptMission,progressMission,completeMission,finishDay,moveHome,starterMissionTemplates};
})();
