(function(){
  function ready(){return window.HauteCoutureCore&&window.HauteCoutureBank}
  function save(s){return HauteCoutureCore.save(s)}
  function enrich(s){if(!s)return s;if(!s.world.feed)s.world.feed=[];if(!s.progression.generatedCount)s.progression.generatedCount=0;if(!s.progression.careerPath)s.progression.careerPath='Libre';const score=(s.missions.completed?.length||0)+(s.player.reputation.local||0)+Math.floor((s.player.reputation.creative||0)*1.5);s.progression.careerLevel=Math.max(s.progression.careerLevel||1,1+Math.floor(score/12));HauteCoutureBank.fillMissions(s,Math.min(10,5+Math.floor(s.progression.careerLevel/2)));s.progression.generatedCount=(s.missions.available||[]).filter(m=>m.generated).length+(s.missions.completed||[]).filter(m=>m.generated).length;return s}
  function loadExtras(){
    if(!window.__HCCharacterExperienceLoading&&!window.__HCCharacterExperienceInstalled){window.__HCCharacterExperienceLoading=true;const ch=document.createElement('script');ch.src='./character-experience-engine.js?v=a06c7a93';ch.onload=()=>{window.__HCCharacterExperienceLoading=false};document.head.appendChild(ch)}
    if(!window.__HCCareerMemoryLoading&&!window.__HCCareerMemoryInstalled){window.__HCCareerMemoryLoading=true;const cm=document.createElement('script');cm.src='./career-memory-engine.js?v=06cacd32';cm.onload=()=>{window.__HCCareerMemoryLoading=false};document.head.appendChild(cm)}
    if(!window.__HCAtelierMemoryTracesLoading&&!window.__HCAtelierMemoryTracesInstalled){window.__HCAtelierMemoryTracesLoading=true;const mt=document.createElement('script');mt.src='./atelier-memory-traces.js?v=ad574b66';mt.onload=()=>{window.__HCAtelierMemoryTracesLoading=false};document.head.appendChild(mt)}
    if(!window.__HCAtelierMemoryLayoutLoading&&!window.__HCAtelierMemoryLayoutInstalled){window.__HCAtelierMemoryLayoutLoading=true;const ml=document.createElement('script');ml.src='./atelier-memory-layout.js?v=59c0e0ca';ml.onload=()=>{window.__HCAtelierMemoryLayoutLoading=false};document.head.appendChild(ml)}
    if(!window.__HCAtelierHomeDnaLoading&&!window.__HCAtelierHomeDnaInstalled){window.__HCAtelierHomeDnaLoading=true;const hd=document.createElement('script');hd.src='./atelier-home-dna.js?v=2e86365f';hd.onload=()=>{window.__HCAtelierHomeDnaLoading=false};document.head.appendChild(hd)}
    if(!window.__HCAtelierUniqueSpaceLoading&&!window.__HCAtelierUniqueSpaceInstalled){window.__HCAtelierUniqueSpaceLoading=true;const us=document.createElement('script');us.src='./atelier-unique-space.js?v=9053c612';us.onload=()=>{window.__HCAtelierUniqueSpaceLoading=false};document.head.appendChild(us)}
    if(!window.__HCFranceGeographyLoading&&!window.__HCFranceGeographyInstalled){window.__HCFranceGeographyLoading=true;const fg=document.createElement('script');fg.src='./france-geography-engine.js?v=6c563790';fg.onload=()=>{window.__HCFranceGeographyLoading=false;loadAinMap()};document.head.appendChild(fg)}else loadAinMap();
    if(!window.__HCHousingPremiumLoading&&!window.__HCHousingPremiumInstalled){window.__HCHousingPremiumLoading=true;const h=document.createElement('script');h.src='./housing-premium-ui.js?v=222081c8';h.onload=()=>{window.__HCHousingPremiumLoading=false};document.head.appendChild(h)}
    if(!window.__HCHousingFlowPolishLoading&&!window.__HCHousingFlowPolishInstalled){window.__HCHousingFlowPolishLoading=true;const hp=document.createElement('script');hp.src='./housing-flow-polish.js?v=f42ec964';hp.onload=()=>{window.__HCHousingFlowPolishLoading=false};document.head.appendChild(hp)}
    if(!window.__HCHousingExperienceLoading&&!window.__HCHousingExperienceInstalled){window.__HCHousingExperienceLoading=true;const hx=document.createElement('script');hx.src='./housing-experience-engine.js?v=57c426f1';hx.onload=()=>{window.__HCHousingExperienceLoading=false};document.head.appendChild(hx)}
    if(!window.__HCHousingVisitDepthLoading&&!window.__HCHousingVisitDepthInstalled){window.__HCHousingVisitDepthLoading=true;const hv=document.createElement('script');hv.src='./housing-visit-depth.js?v=085d62c1';hv.onload=()=>{window.__HCHousingVisitDepthLoading=false};document.head.appendChild(hv)}
    if(!window.__HCCareerUICleanupLoading&&!window.__HCCareerUICleanupInstalled){window.__HCCareerUICleanupLoading=true;const cu=document.createElement('script');cu.src='./career-ui-cleanup.js?v=1774b7bb';cu.onload=()=>{window.__HCCareerUICleanupLoading=false};document.head.appendChild(cu)}
    if(!window.__HCCommsLoading&&!window.__HCCommsInstalled){window.__HCCommsLoading=true;const a=document.createElement('script');a.src='./communication-engine.js?v=694e6a66';a.onload=()=>{window.__HCCommsLoading=false};document.head.appendChild(a)}
    if(!window.__HCDepthLoading&&!window.__HCDepthInstalled){window.__HCDepthLoading=true;const b=document.createElement('script');b.src='./career-depth-engine.js?v=9398905c';b.onload=()=>{window.__HCDepthLoading=false};document.head.appendChild(b)}
    if(!window.__HCProLoading&&!window.__HCProInstalled){window.__HCProLoading=true;const c=document.createElement('script');c.src='./professional-life-engine.js?v=02a5a0a0';c.onload=()=>{window.__HCProLoading=false};document.head.appendChild(c)}
    if(!window.__HCTravelLoading&&!window.__HCTravelInstalled){window.__HCTravelLoading=true;const d=document.createElement('script');d.src='./travel-engine.js?v=e9440310';d.onload=()=>{window.__HCTravelLoading=false;loadAinDeep()};document.head.appendChild(d)}else loadAinDeep();
  }
  function loadAinMap(){if(!window.__HCAinInteractiveMapLoading&&!window.__HCAinInteractiveMapInstalled){window.__HCAinInteractiveMapLoading=true;const m=document.createElement('script');m.src='./ain-interactive-map.js?v=296d5cf0';m.onload=()=>{window.__HCAinInteractiveMapLoading=false;loadBourgMap()};document.head.appendChild(m)}else loadBourgMap()}
  function loadBourgMap(){if(!window.__HCBourgInteractiveMapLoading&&!window.__HCBourgInteractiveMapInstalled){window.__HCBourgInteractiveMapLoading=true;const bm=document.createElement('script');bm.src='./bourg-interactive-map.js?v=7675e12c';bm.onload=()=>{window.__HCBourgInteractiveMapLoading=false;loadMobileMapControls()};document.head.appendChild(bm)}else loadMobileMapControls()}
  function loadMobileMapControls(){if(!window.__HCMobileMapControlsLoading&&!window.__HCMobileMapControlsInstalled){window.__HCMobileMapControlsLoading=true;const mm=document.createElement('script');mm.src='./mobile-map-controls.js?v=1aa34fb9';mm.onload=()=>{window.__HCMobileMapControlsLoading=false};document.head.appendChild(mm)}}
  function loadAinDeep(){if(!window.__HCAinDeepLoading&&!window.__HCAinDeepInstalled){window.__HCAinDeepLoading=true;const e=document.createElement('script');e.src='./travel-ain-deep-engine.js?v=e333c0db';e.onload=()=>{window.__HCAinDeepLoading=false};document.head.appendChild(e)}}
  function install(){if(!ready()||window.__HCInfiniteInstalled)return;window.__HCInfiniteInstalled=true;
    const core=HauteCoutureCore;
    const originalEnsure=core.ensure,originalFinishDay=core.finishDay,originalComplete=core.completeMission,originalInteract=core.interactNeighborhood;
    core.ensure=function(character,residence){let s=originalEnsure(character,residence);s=enrich(s);return save(s)};
    core.finishDay=function(){let s=originalFinishDay();if(!s)return s;s=enrich(s);const evt=HauteCoutureBank.dailyWorldEvent(s);if(!s.world.feed.find(x=>x.id===evt.id)){s.world.feed.unshift(evt);s.messages.push({id:evt.id,from:'Le monde autour de toi',subject:evt.title,body:evt.text,day:s.world.day,read:false});if(evt.kind==='culture')s.inspiration.push({id:'insp-'+evt.id,title:evt.title,source:s.world.currentCity||'Ville',day:s.world.day,used:false,text:evt.text});if(evt.kind==='supplier'&&!s.carnet.suppliers.find(x=>x.id===evt.id))s.carnet.suppliers.push({id:evt.id,name:'Adresse à découvrir',city:s.world.currentCity,day:s.world.day,status:'piste'});}
      const contacts=(s.contacts||[]).filter(c=>(c.relationship||0)>=25&&(c.referrals||0)>0);contacts.forEach((c,i)=>{const already=s.missions.available.some(m=>m.meta?.referralFrom===c.id&&m.createdReferralDay===s.world.day);if(!already&&((s.world.day+i+c.id.length)%5===0)){const m=HauteCoutureBank.referralMission(s,c);m.createdReferralDay=s.world.day;s.missions.available.push(m);c.referrals=Math.max(0,(c.referrals||0)-1);s.messages.push({id:'referral-'+m.id,from:c.name,subject:'Je t’ai recommandée',body:'Une personne de mon entourage cherche quelqu’un pour une pièce. Je lui ai parlé de toi.',day:s.world.day,read:false});}});return save(enrich(s))};
    core.completeMission=function(id){let before=core.load();const previous=(before?.missions?.completed||[]).length;let s=originalComplete(id);if(!s)return s;s=enrich(s);const done=(s.missions.completed||[])[s.missions.completed.length-1];if((s.missions.completed||[]).length>previous&&done){const c=s.contacts.find(x=>x.id===done.clientId);if(c&&(c.relationship||0)>=25&&done.onTime){c.referrals=(c.referrals||0)+1}if(done.generated&&done.meta?.occasion){s.carnet.pages.push({id:'proc-memory-'+done.id,type:'commande',title:'Souvenir de '+done.meta.occasion,text:done.title+' — '+done.client+'. '+done.meta.constraint,createdDay:s.world.day})}}
      return save(enrich(s))};
    core.interactNeighborhood=function(kind){let s=originalInteract(kind);if(!s)return s;if(kind==='mercerie'&&((s.world.day+s.inventory.length)%3===0)){const mat=HauteCoutureBank.materialDiscovery(s,s.inventory.length);s.inventory.push(mat);s.carnet.pages.push({id:'mat-page-'+mat.id,type:'matière',title:'Nouvelle matière : '+mat.name,text:mat.memory,createdDay:s.world.day})}return save(enrich(s))};
    const current=core.load();if(current)save(enrich(current));loadExtras();
  }
  if(ready())install();else{let tries=0;const t=setInterval(()=>{tries++;if(ready()){clearInterval(t);install()}else if(tries>100)clearInterval(t)},50)}
})();