(function(){
  function ready(){return window.HauteCoutureCore&&window.HauteCoutureBank}
  function save(s){return HauteCoutureCore.save(s)}
  function enrich(s){if(!s)return s;if(!s.world.feed)s.world.feed=[];if(!s.progression.generatedCount)s.progression.generatedCount=0;if(!s.progression.careerPath)s.progression.careerPath='Libre';const score=(s.missions.completed?.length||0)+(s.player.reputation.local||0)+Math.floor((s.player.reputation.creative||0)*1.5);s.progression.careerLevel=Math.max(s.progression.careerLevel||1,1+Math.floor(score/12));HauteCoutureBank.fillMissions(s,Math.min(10,5+Math.floor(s.progression.careerLevel/2)));s.progression.generatedCount=(s.missions.available||[]).filter(m=>m.generated).length+(s.missions.completed||[]).filter(m=>m.generated).length;return s}
  function install(){if(!ready()||window.__HCInfiniteInstalled)return;window.__HCInfiniteInstalled=true;
    const core=HauteCoutureCore;
    const originalEnsure=core.ensure,originalFinishDay=core.finishDay,originalComplete=core.completeMission,originalInteract=core.interactNeighborhood;
    core.ensure=function(character,residence){let s=originalEnsure(character,residence);s=enrich(s);return save(s)};
    core.finishDay=function(){let s=originalFinishDay();if(!s)return s;s=enrich(s);const evt=HauteCoutureBank.dailyWorldEvent(s);if(!s.world.feed.find(x=>x.id===evt.id)){s.world.feed.unshift(evt);s.messages.push({id:evt.id,from:'Le monde autour de toi',subject:evt.title,body:evt.text,day:s.world.day,read:false});if(evt.kind==='culture')s.inspiration.push({id:'insp-'+evt.id,title:evt.title,source:s.world.currentCity||'Ville',day:s.world.day,used:false,text:evt.text});if(evt.kind==='supplier'&&!s.carnet.suppliers.find(x=>x.id===evt.id))s.carnet.suppliers.push({id:evt.id,name:'Adresse à découvrir',city:s.world.currentCity,day:s.world.day,status:'piste'});}
      const contacts=(s.contacts||[]).filter(c=>(c.relationship||0)>=25&&(c.referrals||0)>0);contacts.forEach((c,i)=>{const already=s.missions.available.some(m=>m.meta?.referralFrom===c.id&&m.createdReferralDay===s.world.day);if(!already&&((s.world.day+i+c.id.length)%5===0)){const m=HauteCoutureBank.referralMission(s,c);m.createdReferralDay=s.world.day;s.missions.available.push(m);c.referrals=Math.max(0,(c.referrals||0)-1);s.messages.push({id:'referral-'+m.id,from:c.name,subject:'Je t’ai recommandée',body:'Une personne de mon entourage cherche quelqu’un pour une pièce. Je lui ai parlé de toi.',day:s.world.day,read:false});}});return save(enrich(s))};
    core.completeMission=function(id){let before=core.load();const previous=(before?.missions?.completed||[]).length;let s=originalComplete(id);if(!s)return s;s=enrich(s);const done=(s.missions.completed||[])[s.missions.completed.length-1];if((s.missions.completed||[]).length>previous&&done){const c=s.contacts.find(x=>x.id===done.clientId);if(c&&(c.relationship||0)>=25&&done.onTime){c.referrals=(c.referrals||0)+1}if(done.generated&&done.meta?.occasion){s.carnet.pages.push({id:'proc-memory-'+done.id,type:'commande',title:'Souvenir de '+done.meta.occasion,text:done.title+' — '+done.client+'. '+done.meta.constraint,createdDay:s.world.day})}}
      return save(enrich(s))};
    core.interactNeighborhood=function(kind){let s=originalInteract(kind);if(!s)return s;if(kind==='mercerie'&&((s.world.day+s.inventory.length)%3===0)){const mat=HauteCoutureBank.materialDiscovery(s,s.inventory.length);s.inventory.push(mat);s.carnet.pages.push({id:'mat-page-'+mat.id,type:'matière',title:'Nouvelle matière : '+mat.name,text:mat.memory,createdDay:s.world.day})}return save(enrich(s))};
    const current=core.load();if(current)save(enrich(current));
  }
  if(ready())install();else{let tries=0;const t=setInterval(()=>{tries++;if(ready()){clearInterval(t);install()}else if(tries>100)clearInterval(t)},50)}
})();
