(function(){
  function loadCore(cb){if(window.HauteCoutureCore)return cb();const s=document.createElement('script');s.src='./game-core.js?v=3';s.onload=cb;document.head.appendChild(s)}
  function residence(){try{return JSON.parse(localStorage.getItem('haute-couture-residence')||'null')}catch(e){return null}}
  function character(){const id=localStorage.getItem('haute-couture-character');const names={clara:'Clara',ines:'Inès',maya:'Maya',elise:'Élise',salome:'Salomé',anais:'Anaïs',jade:'Jade',camille:'Camille',louise:'Louise',margaux:'Margaux',juliette:'Juliette',romane:'Romane'};return{id,name:names[id]||'Créatrice'}}
  function ensureState(){return HauteCoutureCore.ensure(character(),residence())}
  function injectStyles(){if(document.getElementById('hcHubStyles'))return;const st=document.createElement('style');st.id='hcHubStyles';st.textContent=`
  #atelier .atelier-room{transition:.25s}.hc-stats{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;margin-top:12px}.hc-stat{background:rgba(229,236,224,.88);border-radius:10px;padding:8px;font-size:11px}.hc-stat strong{display:block;font-size:15px;font-weight:400}.hub-btn{cursor:pointer}.hub-btn.active{background:#dfe8d7;border-color:#8fa181}.hc-panel{position:absolute;right:3%;top:5%;bottom:13%;width:min(44%,520px);z-index:12;background:rgba(255,252,245,.97);border:1px solid rgba(82,68,52,.24);border-radius:18px;box-shadow:0 20px 60px rgba(44,34,25,.2);padding:18px;overflow:auto;display:none}.hc-panel.open{display:block}.hc-panel-close{position:absolute;right:12px;top:8px;border:0;background:none;font-size:26px;cursor:pointer}.hc-panel h2{font-size:29px;font-weight:400;margin:4px 0 12px}.hc-card{border:1px solid rgba(82,68,52,.2);background:#fffdf8;border-radius:13px;padding:11px;margin:8px 0}.hc-card h3{font-size:16px;font-weight:400;margin:0 0 5px}.hc-muted{font:12px/1.45 Arial,sans-serif;color:#776e64}.hc-row{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.hc-pill{padding:5px 8px;border-radius:999px;background:#edf1e8;font:11px Arial,sans-serif}.hc-action{border:1px solid rgba(82,68,52,.24);background:#fffaf4;border-radius:999px;padding:8px 11px;font:12px Georgia,serif;cursor:pointer}.hc-action.primary{background:#dfe8d7}.hc-progress{height:7px;border-radius:999px;background:#e5ded3;overflow:hidden;margin-top:7px}.hc-progress i{display:block;height:100%;background:#879879}.hc-empty{text-align:center;padding:18px;color:#85796d;font-size:13px}.hc-memory{border-left:3px solid #9aaa8d;padding-left:10px;margin:10px 0}.hc-object{position:absolute;border:0;background:transparent;cursor:pointer;z-index:6}.hc-object.carnet{left:16%;bottom:29%;width:80px;height:55px}.hc-object.machine{left:20%;bottom:28%;width:110px;height:90px}.hc-object.window{left:8%;top:10%;width:32%;height:34%}.hc-object.boxes{right:8%;bottom:12%;width:110px;height:100px}.hc-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.hc-emotion{font-size:13px;padding:9px 11px;border-radius:12px;background:#f0f3eb}.hc-breakthrough{border-left:3px solid #c79d62;background:#fff8ec}.hc-place{cursor:pointer}.hc-place:hover{background:#f3f6ef}@media(max-width:850px){.hc-panel{left:4%;right:4%;top:6%;bottom:16%;width:auto}.hc-stats{grid-template-columns:repeat(2,1fr)}.hc-grid{grid-template-columns:1fr}}`;
  document.head.appendChild(st)}
  function build(){const atelier=document.querySelector('#atelier .atelier-room');if(!atelier||atelier.dataset.hcUpgraded)return;atelier.dataset.hcUpgraded='1';injectStyles();
    const note=atelier.querySelector('.atelier-note');if(note){note.innerHTML='<div class="kicker">Ton lieu de vie · ton atelier</div><h1 id="atelierTitle">Bienvenue</h1><p id="atelierText"></p><div class="hc-stats"><div class="hc-stat">Argent<strong id="hcMoney">—</strong></div><div class="hc-stat">Jour<strong id="hcDay">—</strong></div><div class="hc-stat">Énergie<strong id="hcEnergy">—</strong></div><div class="hc-stat">Stress<strong id="hcStress">—</strong></div><div class="hc-stat">Humeur<strong id="hcMood">—</strong></div><div class="hc-stat">Inspiration<strong id="hcFlow">—</strong></div></div>'}
    const dock=atelier.querySelector('.hub-docks');if(dock){dock.innerHTML='<button class="hub-btn" data-hc="carnet">📓 Carnet</button><button class="hub-btn" data-hc="agenda">📅 Agenda</button><button class="hub-btn" data-hc="missions">💌 Missions</button><button class="hub-btn" data-hc="contacts">🤝 Contacts</button><button class="hub-btn" data-hc="matieres">🧵 Matières</button><button class="hub-btn" data-hc="inspiration">✦ Inspiration</button><button class="hub-btn" data-hc="portfolio">🖼 Portfolio</button><button class="hub-btn" data-hc="vie">🌿 Vie</button>'}
    const panel=document.createElement('aside');panel.className='hc-panel';panel.id='hcPanel';panel.innerHTML='<button class="hc-panel-close" id="hcClose">×</button><div id="hcPanelBody"></div>';atelier.appendChild(panel);
    [['carnet','hc-object carnet','Carnet'],['missions','hc-object machine','Création / missions'],['inspiration','hc-object window','Observer la lumière'],['matieres','hc-object boxes','Matières & cartons']].forEach(([tab,cls,label])=>{const b=document.createElement('button');b.className=cls;b.dataset.hc=tab;b.setAttribute('aria-label',label);atelier.appendChild(b)});
    atelier.querySelectorAll('[data-hc]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.hc)));document.getElementById('hcClose').onclick=closePanel;renderHub();}
  function closePanel(){const p=document.getElementById('hcPanel');if(p)p.classList.remove('open');document.querySelectorAll('.hub-btn').forEach(b=>b.classList.remove('active'))}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function renderHub(){const s=ensureState();const p=s.home.current;const title=document.getElementById('atelierTitle'),txt=document.getElementById('atelierText');if(title)title.textContent='Bienvenue chez toi, '+s.player.name;if(txt)txt.textContent=(p?.city||'France')+' · '+(p?.type||'Premier logement')+' · '+(p?.surface||'—')+' m². Cet intérieur suivra ton logement et changera lorsque tu déménageras.';const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('hcMoney',s.player.money+' €');set('hcDay','Jour '+s.world.day);set('hcEnergy',s.player.energy+'/100');set('hcStress',s.player.stress+'/100');set('hcMood',s.player.mood);set('hcFlow',s.player.creativeFlow+'/100')}
  function openPanel(tab){const s=ensureState(),body=document.getElementById('hcPanelBody'),panel=document.getElementById('hcPanel');if(!body||!panel)return;document.querySelectorAll('.hub-btn').forEach(b=>b.classList.toggle('active',b.dataset.hc===tab));panel.classList.add('open');const title=t=>'<div class="kicker">'+t[0]+'</div><h2>'+t[1]+'</h2>';
    if(tab==='carnet'){body.innerHTML=title(['Carnet évolutif','Mon carnet'])+(s.carnet.pages.map(p=>'<article class="hc-card"><h3>'+esc(p.title)+'</h3><div class="hc-muted">Jour '+p.createdDay+' · '+esc(p.type)+'</div><p>'+esc(p.text)+'</p></article>').join(''))+'<div class="kicker" style="margin-top:14px">Mémoire de carrière</div>'+s.carnet.careerMemories.map(m=>'<div class="hc-memory"><strong>'+esc(m.title)+'</strong><div class="hc-muted">Jour '+m.day+' · '+esc(m.text)+'</div></div>').join('')+'<div class="kicker" style="margin-top:14px">Objets qui comptent</div>'+s.home.objects.map(o=>'<div class="hc-card"><h3>'+esc(o.name)+'</h3><div class="hc-muted">'+esc(o.story)+'</div></div>').join('')}
    if(tab==='agenda'){body.innerHTML=title(['Temps du jeu','Agenda'])+(s.agenda.deadlines.length?s.agenda.deadlines.map(d=>'<div class="hc-card"><h3>'+esc(d.title)+'</h3><div class="hc-muted">Échéance : jour '+d.day+'</div></div>').join(''):'<div class="hc-empty">Aucune échéance.</div>')+'<div class="hc-row"><button class="hc-action primary" id="hcFinishDay">Terminer la journée</button></div>';setTimeout(()=>{const b=document.getElementById('hcFinishDay');if(b)b.onclick=()=>{HauteCoutureCore.finishDay();renderHub();openPanel('agenda')}},0)}
    if(tab==='missions'){const active=s.missions.active.map(m=>'<article class="hc-card"><h3>'+esc(m.title)+'</h3><div class="hc-muted">'+esc(m.client)+' · échéance jour '+m.deadlineDay+'</div><div class="hc-progress"><i style="width:'+Math.min(100,(m.progress||0)/m.durationHours*100)+'%"></i></div><div class="hc-row"><span class="hc-pill">'+(m.progress||0)+'/'+m.durationHours+' h</span><button class="hc-action primary" onclick="window.HCWork(\''+m.id+'\')">Travailler 2 h</button></div></article>').join('');const avail=s.missions.available.map(m=>'<article class="hc-card"><h3>'+esc(m.title)+'</h3><div class="hc-muted">'+esc(m.client)+' · '+esc(m.brief)+'</div><div class="hc-row"><span class="hc-pill">'+m.budget+' €</span><span class="hc-pill">'+m.durationHours+' h</span><span class="hc-pill">difficulté '+m.difficulty+'</span><button class="hc-action primary" onclick="window.HCAccept(\''+m.id+'\')">Accepter</button></div></article>').join('');body.innerHTML=title(['Carrière','Missions & commandes'])+(active?'<div class="kicker">En cours</div>'+active:'')+(avail?'<div class="kicker" style="margin-top:14px">Disponibles</div>'+avail:'')+(!active&&!avail?'<div class="hc-empty">Aucune mission pour le moment.</div>':'')}
    if(tab==='contacts'){body.innerHTML=title(['Réseau','Mes contacts'])+(s.contacts.length?s.contacts.map(c=>'<article class="hc-card"><h3>'+esc(c.name)+'</h3><div class="hc-muted">'+esc(c.kind)+' · '+esc(c.status)+'</div><div class="hc-row"><span class="hc-pill">Relation '+(c.relationship||0)+'</span><span class="hc-pill">Confiance '+(c.trust||0)+'</span><span class="hc-pill">Recommandations '+(c.referrals||0)+'</span></div>'+(c.notes?.length?'<p class="hc-muted">'+esc(c.notes[c.notes.length-1].text)+'</p>':'')+'</article>').join(''):'<div class="hc-empty">Tes premiers contacts apparaîtront avec les commandes.</div>')}
    if(tab==='matieres'){body.innerHTML=title(['Stock & objets','Matières'])+s.inventory.map(i=>'<article class="hc-card"><h3>'+esc(i.name)+'</h3><div class="hc-muted">'+(i.qty||1)+' '+esc(i.unit||'')+' · qualité '+(i.quality||1)+'</div>'+(i.memory?'<p class="hc-muted">'+esc(i.memory)+'</p>':'')+'</article>').join('')}
    if(tab==='inspiration'){body.innerHTML=title(['Observation','Banque d’inspiration'])+s.inspiration.map(i=>'<article class="hc-card"><h3>'+esc(i.title)+'</h3><div class="hc-muted">Jour '+i.day+' · '+esc(i.source)+'</div><p>'+esc(i.text)+'</p></article>').join('')+'<div class="hc-row"><button class="hc-action" id="hcObserve">Observer par la fenêtre</button></div>';setTimeout(()=>{const b=document.getElementById('hcObserve');if(b)b.onclick=()=>{HauteCoutureCore.observeHome();renderHub();openPanel('inspiration')}},0)}
    if(tab==='portfolio'){body.innerHTML=title(['Mémoire visuelle','Portfolio'])+(s.portfolio.length?s.portfolio.map(p=>'<article class="hc-card '+(p.breakthrough?'hc-breakthrough':'')+'"><h3>'+esc(p.title)+'</h3><div class="hc-muted">Jour '+p.day+' · '+esc(p.location||'')+' · '+esc(p.client||'')+'</div><p>'+esc(p.brief||'')+'</p>'+(p.breakthrough?'<span class="hc-pill">✦ Création marquante</span>':'')+'</article>').join(''):'<div class="hc-empty">Tes créations importantes apparaîtront ici.</div>')}
    if(tab==='vie'){const habits=Object.entries(s.habits).map(([id,h])=>'<article class="hc-card"><h3>'+esc(h.name)+'</h3><div class="hc-muted">Série : '+h.streak+' jour(s)</div><div class="hc-row"><button class="hc-action" onclick="window.HCHabit(\''+id+'\')">Faire maintenant</button></div></article>').join('');const places=s.map.neighborhood.map(p=>'<article class="hc-card hc-place" onclick="window.HCPlace(\''+p.kind+'\')"><h3>'+esc(p.name)+'</h3><div class="hc-muted">'+esc(p.text)+'</div></article>').join('');const surprises=s.surprises.slice(0,4).map(x=>'<article class="hc-card"><h3>'+esc(x.title)+'</h3><div class="hc-muted">Jour '+x.day+'</div><p>'+esc(x.text)+'</p></article>').join('');body.innerHTML=title(['Vie quotidienne','Rythme & quartier'])+'<div class="hc-grid"><div class="hc-emotion"><strong>Humeur</strong><br>'+esc(s.player.mood)+'</div><div class="hc-emotion"><strong>Confiance</strong><br>'+s.player.confidence+'/100</div></div><div class="kicker" style="margin-top:14px">Habitudes</div>'+habits+'<div class="kicker" style="margin-top:14px">Autour de chez toi</div>'+places+'<div class="kicker" style="margin-top:14px">Petits événements</div>'+(surprises||'<div class="hc-empty">Rien de spécial aujourd’hui.</div>')}
  }
  window.HCAccept=id=>{HauteCoutureCore.acceptMission(id);renderHub();openPanel('missions')};window.HCWork=id=>{HauteCoutureCore.progressMission(id,2);renderHub();openPanel('missions')};window.HCHabit=id=>{HauteCoutureCore.doHabit(id);renderHub();openPanel('vie')};window.HCPlace=kind=>{HauteCoutureCore.interactNeighborhood(kind);renderHub();openPanel('vie')};
  function boot(){loadCore(()=>{const old=window.renderAtelier;window.renderAtelier=function(){if(typeof old==='function')old();build();renderHub()};build();if(document.getElementById('atelier')?.classList.contains('active'))renderHub()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
