(function(){
  if(window.__HCTravelInstalled)return;window.__HCTravelInstalled=true;
  const KEY='haute-couture-game-state-v1';
  const places=[
    {id:'ain-soieries-bonnet',name:'Musée des Soieries Bonnet',city:'Jujurieux',kind:'Textile & patrimoine industriel',hours:3,cost:18,tags:['soie','Jacquard','mousseline','velours','tissage'],culture:'Découverte de la soierie, du dessin textile, des métiers du tissage et de la mémoire ouvrière.',creative:'Répétition, chaîne-trame, fluidité, transparence, brillance et motifs façonnés.',unlock:['Foulard Trame','Blouse Mousseline','Veste Façonnée','Jupe Velours Ligne','Motif Répétition Navette'],lesson:['Dessiner un foulard en mouvement','Rendre les plis d’une soie légère','Construire un motif répétitif'],npc:{id:'npc-eleonore-martin',name:'Éléonore Martin',kind:'chargée de collections textiles'}},
    {id:'ain-brou',name:'Monastère royal de Brou',city:'Bourg-en-Bresse',kind:'Architecture & arts',hours:3,cost:16,tags:['gothique','vitrail','pierre','ornement','portrait'],culture:'Architecture, tombeaux, sculpture, vitraux et collections d’art deviennent matière de carnet.',creative:'Verticalité, arcades, pinacles, dentelle de pierre, ivoire, verre coloré et entrelacs.',unlock:['Cape Brou','Col Dentelle de Pierre','Manche Pinacle','Robe Ivoire Monument','Motif Ajour Flamboyant'],lesson:['Transformer une arcade en col','Construire une manche sculpturale','Composer depuis un vitrail'],npc:{id:'npc-lison-girard',name:'Lison Girard',kind:'galeriste'}},
    {id:'ain-parc-oiseaux',name:'Parc des Oiseaux',city:'Villars-les-Dombes',kind:'Nature & mouvement',hours:4,cost:24,tags:['oiseaux','envol','iridescence','plume','mouvement'],culture:'Observation du vivant, de la couleur et du mouvement sans prélèvement.',creative:'Ailes, superpositions, courbes, envol, iridescence et lignes dynamiques.',unlock:['Manche Envol','Jupe Plumage','Motif Plume abstraite','Pose Envol'],lesson:['Transformer une aile en manche','Capturer un mouvement en quelques lignes'],npc:{id:'npc-ines-durand',name:'Inès Durand',kind:'photographe naturaliste'}},
    {id:'ain-voltaire',name:'Château de Voltaire',city:'Ferney-Voltaire',kind:'Maison historique & jardin',hours:3,cost:17,tags:['XVIIIe','jardin','portrait','salon','Lumières'],culture:'Demeure, salons, portraits, jardin régulier et charmille nourrissent une lecture du XVIIIe siècle.',creative:'Axes de jardin, tunnel végétal, portrait, ligne de manteau, botanique et mise en scène sociale.',unlock:['Manteau Charmille','Blouse Conversation','Col Portrait XVIII','Fond Salon des Lumières'],lesson:['Dessiner un col depuis un portrait ancien','Construire une ligne de manteau'],npc:{id:'npc-celeste-roche',name:'Céleste Roche',kind:'programmatrice culturelle'}},
    {id:'ain-oyonnax-peigne',name:'Musée du Peigne et de la Plasturgie',city:'Oyonnax',kind:'Design & accessoires',hours:3,cost:15,tags:['peigne','lunettes','acétate','design','accessoire'],culture:'Histoire du peigne, de l’ornement de coiffure, des matières transformées et du design industriel.',creative:'Facettes, transparence, modules, plaques, courbes d’accessoires et répétition.',unlock:['Peigne sculptural','Lunettes Acétate','Top Plaques','Jupe Disques'],lesson:['Dessiner un accessoire de tête','Construire une forme modulaire'],npc:{id:'npc-sanae-morel',name:'Sanaé Morel',kind:'designer accessoires'}},
    {id:'ain-cerdon-cuivrerie',name:'Cuivrerie de Cerdon',city:'Cerdon',kind:'Métal & savoir-faire',hours:2,cost:14,tags:['cuivre','martelage','repoussé','patine','artisanat'],culture:'Observation du travail du cuivre, du martelage et de la transformation de la feuille métallique.',creative:'Rigidité, reflet, martelage, courbe embossée et patine cuivre/vert-de-gris.',unlock:['Col Cuivre','Manchette Martelée','Ceinture Métal','Texture Repoussé'],lesson:['Dessiner une surface métallique','Transformer un martelage en motif'],npc:{id:'npc-gaspard-renard',name:'Gaspard Renard',kind:'artisan métal'}},
    {id:'ain-trevoux-art',name:'Trévoux — ville d’art et d’histoire',city:'Trévoux',kind:'Artisanat d’art',hours:3,cost:8,tags:['filigrane','bijou','fil d’or','céramique','artisanat'],culture:'Le patrimoine et les métiers d’art ouvrent une branche centrée sur l’ornement et la précision.',creative:'Filigrane, ligne fine, médaillon, métal doré et motifs délicats.',unlock:['Ceinture Fil d’Or','Boucles Filigrane','Broderie métallique fine'],lesson:['Passer du filigrane au motif textile','Dessiner un bijou à l’échelle du corps'],npc:{id:'npc-nora-fabre',name:'Nora Fabre',kind:'bijoutière'}},
    {id:'ain-perouges-town',name:'Cité médiévale de Pérouges',city:'Pérouges',kind:'Village & architecture',hours:3,cost:7,tags:['pierre','bois','pavé','patine','artisanat'],culture:'Ruelles, façades, matériaux et traces du temps deviennent une page de carnet minérale.',creative:'Capuches, ceintures, surfaces patinées, tons de pierre et géométrie de façade.',unlock:['Capuche Cité','Ceinture Patine','Texture Pavé'],lesson:['Construire une capuche simple','Rendre pierre, bois et patine'],npc:{id:'npc-maud-perrin',name:'Maud Perrin',kind:'artisane cuir'}},
    {id:'ain-mijoux-lapidaire',name:'Musée des pierres et du lapidaire',city:'Mijoux',kind:'Pierre fine & bijou',hours:2,cost:12,tags:['lapidaire','facette','pierre','bijou','transparence'],culture:'La taille de pierre fine devient une entrée vers le bijou, la précision et les effets de lumière.',creative:'Facettes, éclat, transparence, géométrie et rapport bijou-corps.',unlock:['Col Facetté','Ceinture Gemme','Broche Minérale'],lesson:['Dessiner une facette','Rendre transparence et éclat','Dessiner un bijou porté'],npc:{id:'npc-camille-rey',name:'Camille Rey',kind:'lapidaire'}},
    {id:'ain-oncieu',name:'Oncieu — village en cercle',city:'Oncieu',kind:'Urbanisme & patronage',hours:2,cost:5,tags:['cercle','radial','village','patronage','géométrie'],culture:'Le plan circulaire du village devient une leçon de composition spatiale.',creative:'Cercle, centre, rayons, anneaux et construction autour d’un point fixe.',unlock:['Jupe Cercle Oncieu','Top Radial','Col Anneau'],lesson:['Construire une jupe cercle','Créer un vêtement autour d’un centre'],npc:null},
    {id:'ain-fort-ecluse',name:'Fort l’Écluse',city:'Léaz',kind:'Fortification & structure',hours:4,cost:18,tags:['fort','escalier','roche','structure','utilitaire'],culture:'Architecture défensive, casemates, portes, terrasses et circulation verticale.',creative:'Rythme d’escalier, poches, fentes, protection, panneaux et lignes militaires réinterprétées.',unlock:['Manteau Écluse','Poche Fortifiée','Jupe Escalier'],lesson:['Construire un manteau utilitaire','Transformer un escalier en rythme de plis'],npc:{id:'npc-yasmine-keller',name:'Yasmine Keller',kind:'scénographe'}},
    {id:'ain-grand-colombier',name:'Grand Colombier',city:'Bugey',kind:'Paysage & montagne',hours:5,cost:10,tags:['montagne','vent','crête','pli','protection'],culture:'Relief, vent et horizon deviennent une observation de volumes et de protection du corps.',creative:'Crêtes, plis géologiques, capuches, superpositions et silhouettes poussées par le vent.',unlock:['Cape de Crête','Capuche Colombier','Panneau Relief'],lesson:['Dessiner un vêtement poussé par le vent','Transformer un relief en volume'],npc:{id:'npc-simon-borel',name:'Simon Borel',kind:'guide et photographe de montagne'}}
  ];
  function load(){try{return window.HauteCoutureCore?.load?.()||JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){return null}}
  function save(s){if(window.HauteCoutureCore?.save)return HauteCoutureCore.save(s);localStorage.setItem(KEY,JSON.stringify(s));return s}
  function ensureTravel(s){s.travel=s.travel||{visited:[],unlocks:[],lessons:[],keywords:[],currentDepartment:null};s.travel.visited=s.travel.visited||[];s.travel.unlocks=s.travel.unlocks||[];s.travel.lessons=s.travel.lessons||[];s.travel.keywords=s.travel.keywords||[];return s}
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function saveNow(){const s=load();if(s)save(s);localStorage.setItem('haute-couture-current-screen','atelier');const t=document.getElementById('hcSaveToast');if(t){t.textContent='Partie sauvegardée';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}}
  function goHome(){saveNow();if(typeof window.displayScreen==='function')window.displayScreen('home');else location.href='./'}
  function injectUtility(){if(document.getElementById('hcUtilityBar'))return;const host=document.querySelector('#atelier .atelier-room')||document.body;const bar=document.createElement('div');bar.id='hcUtilityBar';bar.innerHTML='<button id="hcGoHome">⌂ Accueil</button><button id="hcSaveGame">💾 Sauvegarder</button><span id="hcSaveToast">Partie sauvegardée</span>';host.appendChild(bar);bar.querySelector('#hcGoHome').onclick=goHome;bar.querySelector('#hcSaveGame').onclick=saveNow;const st=document.createElement('style');st.textContent='#hcUtilityBar{position:absolute;left:16px;top:16px;z-index:45;display:flex;gap:7px;align-items:center}#hcUtilityBar button{border:1px solid rgba(82,68,52,.28);background:rgba(255,252,245,.94);padding:8px 11px;border-radius:999px;font:12px Georgia,serif;cursor:pointer;box-shadow:0 4px 14px rgba(55,45,35,.08)}#hcUtilityBar button:hover{background:#edf2e8}#hcSaveToast{opacity:0;transform:translateY(-5px);transition:.18s;background:#718066;color:white;padding:7px 10px;border-radius:999px;font:11px Arial,sans-serif;pointer-events:none}#hcSaveToast.show{opacity:1;transform:none}@media(max-width:700px){#hcUtilityBar{top:8px;left:8px}#hcUtilityBar button{padding:7px 9px}}';document.head.appendChild(st)}
  function visit(id){let s=load();if(!s)return;ensureTravel(s);const p=places.find(x=>x.id===id);if(!p)return;const already=s.travel.visited.find(x=>x.id===id);if(already){open();return}
    s.player.money=Math.max(0,(s.player.money||0)-p.cost);s.world.hour=(s.world.hour||9)+p.hours;while(s.world.hour>=24){s.world.hour-=24;s.world.day+=1}
    s.player.energy=Math.max(0,(s.player.energy||100)-p.hours*4);s.player.creativeFlow=Math.min(100,(s.player.creativeFlow||0)+8);s.world.currentDepartment='Ain';s.world.currentRegion='Auvergne-Rhône-Alpes';s.world.currentCity=p.city;
    s.travel.visited.push({id:p.id,name:p.name,city:p.city,day:s.world.day,tags:p.tags});p.unlock.forEach(x=>{if(!s.travel.unlocks.includes(x))s.travel.unlocks.push(x)});p.lesson.forEach(x=>{if(!s.travel.lessons.includes(x))s.travel.lessons.push(x)});p.tags.forEach(x=>{if(!s.travel.keywords.includes(x))s.travel.keywords.push(x)});
    s.carnet.pages.push({id:'travel-'+p.id+'-'+Date.now(),type:'voyage',title:p.name,text:p.culture+'\n\nLecture créative : '+p.creative+'\n\nDébloqué : '+p.unlock.join(', ')+'.\nCours : '+p.lesson.join(', ')+'.',createdDay:s.world.day});
    s.inspiration.push({id:'travel-insp-'+p.id,title:p.name+' — inspiration',source:p.city,day:s.world.day,used:false,text:p.creative});
    if(p.npc&&!s.contacts.find(c=>c.id===p.npc.id)&&((s.world.day+p.id.length)%3!==0)){s.contacts.push({id:p.npc.id,name:p.npc.name,kind:p.npc.kind,status:'Rencontre de voyage',relationship:4,trust:2,referrals:0,metDay:s.world.day,lastInteractionDay:s.world.day,notes:[{day:s.world.day,text:'Rencontré·e pendant la visite de '+p.name+'.'}]})}
    s.messages.push({id:'travel-msg-'+p.id,from:'Carnet de voyage',subject:'Souvenir ajouté : '+p.name,body:'La visite a enrichi ton carnet et débloqué de nouvelles pistes de création.',day:s.world.day,read:false});save(s);open();
  }
  function render(){const s=ensureTravel(load()||{}),visited=new Set((s.travel.visited||[]).map(x=>x.id));const cards=places.map(p=>'<article class="hc-travel-card '+(visited.has(p.id)?'visited':'')+'"><div class="hc-travel-top"><div><div class="hc-travel-kind">'+esc(p.kind)+'</div><h3>'+esc(p.name)+'</h3><div class="hc-travel-city">'+esc(p.city)+' · Ain</div></div><span class="hc-travel-state">'+(visited.has(p.id)?'✓ Visité':'À découvrir')+'</span></div><p>'+esc(p.culture)+'</p><div class="hc-travel-tags">'+p.tags.slice(0,5).map(t=>'<span>'+esc(t)+'</span>').join('')+'</div><details><summary>Ce que ça peut nourrir</summary><p>'+esc(p.creative)+'</p><strong>Déblocages</strong><p>'+esc(p.unlock.join(' · '))+'</p><strong>Cours de dessin</strong><p>'+esc(p.lesson.join(' · '))+'</p></details><button class="hc-travel-go" onclick="window.HCTravelVisit(\''+p.id+'\')" '+(visited.has(p.id)?'disabled':'')+'>'+(visited.has(p.id)?'Déjà dans le carnet':'Visiter · '+p.hours+' h · '+p.cost+' €')+'</button></article>').join('');return '<div class="hc-travel-head"><div class="kicker">Voyage · culture · création</div><h2>Explorer l’Ain</h2><p>Cette première vue de test ne représente pas la densité finale du département. On bascule maintenant vers les visuels avant de continuer à enrichir la base.</p><div class="hc-travel-count">'+visited.size+' / '+places.length+' lieux de test · '+(s.travel.unlocks?.length||0)+' éléments créatifs · '+(s.travel.lessons?.length||0)+' cours</div></div><div class="hc-travel-list">'+cards+'</div>'}
  function open(){const panel=document.getElementById('hcTravelPanel');if(!panel)return;const body=panel.querySelector('.hc-travel-body');body.innerHTML=render();panel.classList.add('open')}
  function close(){document.getElementById('hcTravelPanel')?.classList.remove('open')}
  function inject(){const atelier=document.querySelector('#atelier .atelier-room');const dock=atelier?.querySelector('.hub-docks');if(!atelier||!dock||document.getElementById('hcTravelPanel'))return false;
    injectUtility();const b=document.createElement('button');b.className='hub-btn';b.innerHTML='🗺 Voyage';b.onclick=open;dock.appendChild(b);
    const p=document.createElement('aside');p.id='hcTravelPanel';p.className='hc-travel-panel';p.innerHTML='<button class="hc-travel-close" aria-label="Fermer">×</button><div class="hc-travel-body"></div>';atelier.appendChild(p);p.querySelector('.hc-travel-close').onclick=close;
    if(!document.getElementById('hcTravelStyles')){const st=document.createElement('style');st.id='hcTravelStyles';st.textContent='.hc-travel-panel{position:absolute;inset:4% 3% 12% 30%;z-index:25;background:rgba(248,246,238,.985);border:1px solid rgba(73,84,68,.25);box-shadow:0 24px 70px rgba(40,45,37,.2);padding:22px;overflow:auto;display:none}.hc-travel-panel.open{display:block}.hc-travel-close{position:sticky;float:right;top:0;border:0;background:transparent;font-size:28px;cursor:pointer;z-index:2}.hc-travel-head h2{font:34px Georgia,serif;font-weight:400;margin:4px 0 8px}.hc-travel-head p{max-width:760px;color:#665f56}.hc-travel-count{background:#e4ebdd;padding:10px 12px;margin:12px 0 18px;font:12px Arial,sans-serif}.hc-travel-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.hc-travel-card{background:#fffdf8;border:1px solid rgba(73,84,68,.2);padding:13px}.hc-travel-card.visited{background:#f1f5ed}.hc-travel-top{display:flex;justify-content:space-between;gap:10px}.hc-travel-card h3{font:18px Georgia,serif;font-weight:400;margin:2px 0}.hc-travel-kind,.hc-travel-city,.hc-travel-state{font:11px Arial,sans-serif;color:#786f64}.hc-travel-state{white-space:nowrap}.hc-travel-card p{font:13px/1.45 Georgia,serif}.hc-travel-tags{display:flex;gap:5px;flex-wrap:wrap}.hc-travel-tags span{background:#edf1e8;padding:4px 7px;font:10px Arial,sans-serif}.hc-travel-card details{margin-top:9px;border-top:1px solid #e6dfd5;padding-top:8px}.hc-travel-card summary{cursor:pointer;font:12px Arial,sans-serif}.hc-travel-go{width:100%;margin-top:10px;padding:9px;border:1px solid #8c9b80;background:#dfe8d7;font:12px Georgia,serif;cursor:pointer}.hc-travel-go:disabled{opacity:.5;cursor:default}@media(max-width:900px){.hc-travel-panel{inset:5% 4% 15%}.hc-travel-list{grid-template-columns:1fr}}';document.head.appendChild(st)}return true}
  window.HCTravelVisit=visit;window.HCTravel={open,render,places};let tries=0;const timer=setInterval(()=>{tries++;if(inject()||tries>120)clearInterval(timer)},100);
})();