/* Haute Couture Live — Café des Croquis Nîmes v2.
   Lieu social : ambiance du jour, Yannis, scènes, rumeurs, rencontres et mémoire persistante.
*/
(function(){
'use strict';
const STATEKEY='haute-couture-nimes-cafe-state-v2',CHOICEKEY='haute-couture-narrative-choices-v1',RUMOURKEY='haute-couture-nimes-rumours-v1';
const $=s=>document.querySelector(s),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch(e){return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const day=()=>Number(window.HCGame?.get?.().clock?.day||1),stamp=()=>window.HCGame?.get?.().clock?.iso||new Date().toISOString(),money=()=>Number(window.HCGame?.get?.().player?.money||0),fmt=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const YANNIS={id:'nimes-yannis-roux',firstName:'Yannis',lastName:'Roux',role:'Gérant du Café des Croquis · connecteur social',image:'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=900',bio:'Yannis connaît les habitudes du quartier, les habitués, les gens de passage et surtout qui parle avec qui. Il n’est ni agent ni recruteur : il tient son café. Mais il se souvient des visages, des conversations et des personnes qui reviennent sans toujours vouloir obtenir quelque chose.',traits:['Sociable','Fin observateur','Discret','Très bon souvenir des gens'],likes:'Les personnes naturelles, celles qui discutent sans forcer et qui reviennent aussi quand elles n’ont rien à demander.',unlock:'Avec le temps, Yannis peut devenir un contact fiable : il pourra te transmettre une invitation, te prévenir qu’une personne est passée ou te mettre en relation sans que cela arrive automatiquement.'};
const SCENES=[
 {id:'window-slow',image:'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=1400',kicker:'MATIN CALME',title:'Une table près de la fenêtre',text:'Le café est encore tranquille. Une femme travaille sur un ordinateur au fond, deux habitués lisent le journal, et Yannis installe des verres derrière le comptoir. Rien ne semble urgent.',person:null,actions:['sit','yannis','observe','leave']},
 {id:'shooting-talk',image:'https://images.pexels.com/photos/2074130/pexels-photo-2074130.jpeg?auto=compress&cs=tinysrgb&w=1400',kicker:'CONVERSATION AU COMPTOIR',title:'Un shooting dont personne ne donne vraiment le nom',text:'Deux personnes parlent à voix basse d’une série photo prévue bientôt. Tu entends les mots “silhouette”, “retouche” et “vendredi”, mais pas assez pour comprendre le projet.',person:'Noé Carrière',actions:['sit','listen','yannis','leave']},
 {id:'yannis-posters',image:'https://images.pexels.com/photos/1855214/pexels-photo-1855214.jpeg?auto=compress&cs=tinysrgb&w=1400',kicker:'FIN D’APRÈS-MIDI',title:'Yannis décroche de vieilles affiches',text:'Le café se vide. Yannis trie quelques affiches d’événements passés et garde à part une invitation imprimée qu’il hésite à jeter.',person:null,actions:['yannis','askPoster','sit','leave']},
 {id:'busy-room',image:'https://images.pexels.com/photos/1307698/pexels-photo-1307698.jpeg?auto=compress&cs=tinysrgb&w=1400',kicker:'COUP DE FEU',title:'Aujourd’hui, tout le monde parle en même temps',text:'La salle est pleine. Impossible de distinguer une conversation. Yannis te reconnaît mais n’a presque pas une minute. C’est un de ces jours où venir ici ne garantit absolument rien.',person:null,actions:['sit','wave','leave']}
];
function state(){const s=read(STATEKEY,{});return {relation:Number(s.relation||0),visits:Number(s.visits||0),lastDay:Number(s.lastDay||0),seen:s.seen||{},heard:s.heard||{}}}function saveState(s){write(STATEKEY,s)}
function relationLabel(n){if(n>=7)return'Habituée du lieu';if(n>=4)return'Yannis te connaît bien';if(n>=2)return'Il te reconnaît';return'Premiers échanges'}
function record(choice,effect){let arr=read(CHOICEKEY,[]);arr.unshift({day:day(),context:'nimes-cafe-creative',choice,effect,at:stamp()});write(CHOICEKEY,arr.slice(0,300))}
function refreshWallet(){const el=$('#npWalletAmount');if(el)el.textContent=fmt(money())}function spend(n,label){if(n>money())return false;window.HCGame?.transact?.(-n,label,'ville');refreshWallet();return true}
function addRumour(id,title,text){let arr=read(RUMOURKEY,[]);if(arr.some(x=>x.id===id))return false;arr.unshift({id,title,text,city:'Nîmes',day:day(),source:'Café des Croquis',at:stamp()});write(RUMOURKEY,arr.slice(0,100));window.dispatchEvent(new CustomEvent('hc-rumour',{detail:arr[0]}));return true}
function css(){if($('#hcCafeV2Style'))return;const s=document.createElement('style');s.id='hcCafeV2Style';s.textContent=`
.ncv2-top{display:grid;grid-template-columns:1.4fr .6fr;gap:14px;margin-bottom:14px}.ncv2-hero,.ncv2-person{background:#fffdf9;border:1px solid #e7d8cc;border-radius:22px;overflow:hidden;box-shadow:0 8px 22px #6b4a3410}.ncv2-hero{position:relative;min-height:390px;background:#ddd}.ncv2-hero img{width:100%;height:390px;object-fit:cover;display:block}.ncv2-over{position:absolute;inset:auto 0 0;padding:60px 20px 18px;background:linear-gradient(180deg,transparent,#1f1713d9);color:#fff}.ncv2-kicker{font-size:8px;letter-spacing:.16em;font-weight:900}.ncv2-over h3{font:42px/.95 Georgia,serif;margin:5px 0 7px}.ncv2-over p{font:13px/1.55 Georgia,serif;margin:0;max-width:760px}.ncv2-person{padding:12px}.ncv2-person img{width:100%;height:190px;object-fit:cover;border-radius:16px}.ncv2-person h3{font:28px/.95 Georgia,serif;margin:10px 0 4px}.ncv2-person p{font:11px/1.5 Georgia,serif;color:#67574f}.ncv2-rel{display:inline-block;border:1px solid #dfcfc2;background:#fff;border-radius:999px;padding:6px 9px;font-size:8px;font-weight:900}.ncv2-btn{border:0;border-radius:11px;background:#211a16;color:#fff;padding:11px 13px;font-size:9px;font-weight:900;cursor:pointer}.ncv2-btn.alt{background:#efe3d9;color:#211a16}.ncv2-btn.soft{background:#fff;border:1px solid #dfcfc2;color:#211a16}.ncv2-actions{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.ncv2-scene{max-width:930px;margin:auto}.ncv2-card{background:#fffdf9;border:1px solid #e7d8cc;border-radius:22px;padding:18px}.ncv2-card h3{font:38px/.95 Georgia,serif;margin:4px 0 9px}.ncv2-card p{font:14px/1.65 Georgia,serif;color:#5f5149}.ncv2-result{display:grid;grid-template-columns:.85fr 1.15fr;gap:18px;align-items:start}.ncv2-result img{width:100%;height:360px;object-fit:cover;border-radius:20px}.ncv2-note{background:#fff1e9;border:1px dashed #d9bbaa;border-radius:14px;padding:12px;font:12px/1.5 Georgia,serif;color:#6d5b51;margin-top:12px}.ncv2-facts{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.ncv2-fact{background:#fff;border:1px solid #eadfd6;border-radius:13px;padding:10px}.ncv2-fact small{display:block;font-size:7px;letter-spacing:.12em;font-weight:900;color:#9a7f70;margin-bottom:4px}.ncv2-fact span{font:12px/1.45 Georgia,serif}.ncv2-nav{display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap;margin-bottom:13px}@media(max-width:900px){.ncv2-top,.ncv2-result{grid-template-columns:1fr}.ncv2-person{display:grid;grid-template-columns:150px 1fr;gap:12px}.ncv2-person img{height:150px}.ncv2-actions{grid-template-columns:1fr 1fr}}@media(max-width:560px){.ncv2-actions,.ncv2-person{grid-template-columns:1fr}.ncv2-hero,.ncv2-hero img{min-height:300px;height:300px}}
`;document.head.appendChild(s)}
function profile(body,place,scene){const s=state();body.innerHTML=`<div class="ncv2-nav"><button class="ncv2-btn soft" id="backCafe">← RETOUR AU CAFÉ</button><button class="ncv2-btn soft" data-city>RETOUR À LA VILLE</button></div><div class="ncv2-scene"><div class="ncv2-result"><img src="${YANNIS.image}" alt="${YANNIS.firstName} ${YANNIS.lastName}"><div class="ncv2-card"><div class="ncv2-kicker">PERSONNAGE · CAFÉ DES CROQUIS</div><h3>${YANNIS.firstName} ${YANNIS.lastName}</h3><div class="ncv2-rel">${relationLabel(s.relation)} · ${s.relation}</div><p>${YANNIS.bio}</p><div class="ncv2-facts"><div class="ncv2-fact"><small>RÔLE</small><span>${YANNIS.role}</span></div><div class="ncv2-fact"><small>PERSONNALITÉ</small><span>${YANNIS.traits.join(' · ')}</span></div><div class="ncv2-fact"><small>CE QU’IL APPRÉCIE</small><span>${YANNIS.likes}</span></div><div class="ncv2-fact"><small>DANS TA CARRIÈRE</small><span>${YANNIS.unlock}</span></div></div><div class="ncv2-note">Personnage fictif créé pour le gameplay de Nîmes.</div></div></div></div>`;$('#backCafe').onclick=()=>render(body,place,scene);body.querySelector('[data-city]').onclick=()=>window.HCNimesPlaceUI?.close?.()}
function actionLabel(a){return {sit:'M’INSTALLER',yannis:'PARLER À YANNIS',observe:'OBSERVER LA SALLE',listen:'ÉCOUTER DISCRÈTEMENT',leave:'REPARTIR',askPoster:'LUI DEMANDER POUR L’AFFICHE',wave:'LUI FAIRE UN SIGNE'}[a]||a}
function render(body,place,forcedScene){let s=state();if(s.lastDay!==day()){s.lastDay=day();s.visits+=1;saveState(s)}const scene=forcedScene||SCENES[(day()+2)%SCENES.length];body.innerHTML=`<div class="ncv2-nav"><button class="ncv2-btn soft" data-city>← RETOUR À LA VILLE</button><div class="ncv2-rel">${relationLabel(s.relation)} · ${s.relation}</div></div><div class="ncv2-top"><section class="ncv2-hero"><img src="${scene.image}" alt="Ambiance du Café des Croquis"><div class="ncv2-over"><div class="ncv2-kicker">${scene.kicker}</div><h3>${scene.title}</h3><p>${scene.text}</p></div></section><aside class="ncv2-person"><img src="${YANNIS.image}" alt="${YANNIS.firstName} ${YANNIS.lastName}"><div><div class="ncv2-kicker">AU COMPTOIR</div><h3>${YANNIS.firstName} ${YANNIS.lastName}</h3><p>${YANNIS.role}</p><button class="ncv2-btn alt" id="openYannis">VOIR SA FICHE</button></div></aside></div><div class="ncv2-actions">${scene.actions.map(a=>`<button class="ncv2-btn ${a==='leave'?'soft':'alt'}" data-act="${a}">${actionLabel(a)}</button>`).join('')}</div><div class="ncv2-note">Une visite ici ne garantit ni rencontre, ni rumeur, ni opportunité. Le café est aussi un endroit où il peut simplement ne rien se passer.</div>`;body.querySelector('[data-city]').onclick=()=>window.HCNimesPlaceUI?.close?.();$('#openYannis').onclick=()=>profile(body,place,scene);body.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(body,place,scene,b.dataset.act))}
function result(body,place,scene,title,text,image,note){body.innerHTML=`<div class="ncv2-nav"><button class="ncv2-btn soft" id="backCafe">← RETOUR AU CAFÉ</button><button class="ncv2-btn soft" data-city>RETOUR À LA VILLE</button></div><div class="ncv2-scene"><div class="ncv2-result"><img src="${image||scene.image}" alt="${esc(title)}"><div class="ncv2-card"><div class="ncv2-kicker">CAFÉ DES CROQUIS · SCÈNE</div><h3>${esc(title)}</h3><p>${esc(text)}</p>${note?`<div class="ncv2-note">${esc(note)}</div>`:''}</div></div></div>`;$('#backCafe').onclick=()=>render(body,place,scene);body.querySelector('[data-city]').onclick=()=>window.HCNimesPlaceUI?.close?.()}
function act(body,place,scene,a){const s=state();if(a==='leave'){record('partir',{});window.HCNimesPlaceUI?.close?.();return}if(a==='sit'){if(!spend(5,'Café — '+place.name)){result(body,place,scene,'Pas aujourd’hui','Tu regardes ton portefeuille et décides de garder tes euros pour autre chose.',scene.image,'Aucune conséquence négative.');return}window.HCGame?.advanceTime?.(35,'Pause au '+place.name);s.relation+=s.seen['sit-'+day()]?0:1;s.seen['sit-'+day()]=true;saveState(s);record('s-installer',{price:5,time:35,relation:s.relation});result(body,place,scene,'Tu t’installes un moment','Tu commandes quelque chose de simple et tu regardes la salle vivre autour de toi. Personne ne vient forcément te parler. Yannis te reconnaît un peu mieux simplement parce que tu reviens et que tu prends le temps.',scene.image,'5 € · 35 min de jeu · la relation peut progresser, sans opportunité garantie.');return}
if(a==='yannis'){window.HCGame?.advanceTime?.(15,'Discussion avec Yannis');if(!s.seen['talk-'+day()]){s.relation+=1;s.seen['talk-'+day()]=true;saveState(s)}record('parler-yannis',{relation:s.relation});result(body,place,scene,'Quelques minutes avec Yannis','Il te demande comment avance ton travail, puis la conversation dérive sur les gens du quartier. Il ne te donne pas automatiquement une piste : aujourd’hui, il apprend surtout à te connaître.',YANNIS.image,relationLabel(s.relation)+' · relation '+s.relation);return}
if(a==='observe'){window.HCGame?.advanceTime?.(15,'Observer le Café des Croquis');record('observer-salle',{scene:scene.id});result(body,place,scene,'Tu regardes sans provoquer la scène','Tu remarques les habitudes, les vêtements, les gestes et les petits groupes. Rien de spectaculaire ne se produit. Mais la ville paraît un peu moins abstraite quand tu commences à reconnaître ses rythmes.',scene.image,'15 min de jeu · aucune récompense automatique.');return}
if(a==='listen'){window.HCGame?.advanceTime?.(20,'Écouter une conversation au Café des Croquis');const fresh=addRumour('nimes-rumour-shoot-'+day(),'Un shooting cherche peut-être quelqu’un','Une conversation au Café des Croquis évoque une série photo prochaine et un besoin autour d’une silhouette ou d’une retouche. Rien n’est confirmé.');s.heard[scene.id]=true;saveState(s);record('ecouter',{rumour:fresh,scene:scene.id});result(body,place,scene,'Tu captes quelques mots','Tu n’obtiens ni nom complet ni rendez-vous, seulement une piste : un shooting se prépare et quelqu’un pourrait chercher une personne capable de travailler vite sur une silhouette.',scene.image,fresh?'Une rumeur est mémorisée. Elle pourra être confirmée — ou rester une simple rumeur.':'Tu avais déjà entendu cette rumeur aujourd’hui.');return}
if(a==='askPoster'){window.HCGame?.advanceTime?.(10,'Parler de l’affiche avec Yannis');const fresh=addRumour('nimes-poster-private-'+day(),'Une invitation imprimée oubliée','Yannis hésitait à jeter une ancienne invitation liée à un événement créatif. Il dit qu’un événement similaire pourrait revenir, mais ne promet rien.');if(!s.seen['poster-'+day()]){s.relation+=1;s.seen['poster-'+day()]=true;saveState(s)}record('demander-affiche',{rumour:fresh,relation:s.relation});result(body,place,scene,'« Celle-là ? Elle date déjà un peu. »','Yannis retourne l’invitation dans sa main. Il t’explique où elle circulait et pourquoi certains créatifs du coin en parlaient. Il ajoute qu’il te dira s’il entend parler d’une nouvelle édition.',YANNIS.image,fresh?'Une piste contextuelle est mémorisée. Ce n’est pas encore une invitation.':'Tu connais déjà cette histoire.');return}
if(a==='wave'){record('faire-signe',{});result(body,place,scene,'Un signe depuis la salle','Yannis te répond d’un sourire rapide avant de repartir servir. Aujourd’hui, c’est tout. Et c’est précisément ce qui rend le lieu crédible : le monde continue même quand il n’a rien à te donner.',scene.image,'Aucune récompense. Aucun malus.');return}}
function install(){const ui=window.HCNimesPlaceUI;if(!ui?.routes?.['nimes-cafe-creative']){setTimeout(install,80);return}css();const original=ui.routes['nimes-cafe-creative'];function openV2(place){original(place);const body=$('#npBody');if(!body)return true;refreshWallet();render(body,place);return true}openV2.__ncv2=true;ui.routes['nimes-cafe-creative']=openV2}
install();window.HCNimesCafe={Yannis:YANNIS,scenes:SCENES};
})();